In [1]:
import os
import networkx as nx
import pandas as pd
import numpy as np
import time
import subprocess
import shlex
from Bio.Blast import NCBIXML
from collections import defaultdict
import warnings
from itertools import compress, count, islice
from functools import partial
from operator import eq
import argparse
import logging
import copy
import MHG_partition
warnings.filterwarnings('ignore')

In [2]:
def parseBlastXML(filePath):
    """
    Convert a blast xml file to a dataframe storing all pairwise mapping information
    """ 
    queryList, subjectList, percentIdentityList, alignmentLenList, mismatchList, gapList, qStartList, qEndList, sStartList, sEndList, evalList, bitScoreList, qSeqList, sSeqList = [],[],[],[],[],[],[],[],[],[],[],[],[],[]
    f = open(filePath)
    blast_records = NCBIXML.parse(f)
    for blast_record in blast_records:
        queryAccVer = blast_record.query[:blast_record.query.find(" ")] if blast_record.query.find(" ")!= -1 else blast_record.query
        for alignment in blast_record.alignments:
            subjectAccVer = alignment.hit_def[:alignment.hit_def.find(' ')] if alignment.hit_def.find(" ")!= -1 else alignment.hit_def
            for hsp in alignment.hsps:
                percentIdentity = round(hsp.identities/hsp.align_length*100,3)
                alignLength = hsp.align_length
                mismatch = hsp.align_length - hsp.identities - hsp.gaps
                gaps = hsp.gaps
                qStart = hsp.query_start
                qEnd = hsp.query_end
                sStart = hsp.sbjct_start
                sEnd = hsp.sbjct_end
                evalue = hsp.expect
                bitScore = int(hsp.bits)
                qSeq = hsp.query
                sSeq = hsp.sbjct
                
                queryList.append(queryAccVer)
                subjectList.append(subjectAccVer)
                percentIdentityList.append(percentIdentity)
                alignmentLenList.append(alignLength)
                mismatchList.append(mismatch)
                gapList.append(gaps)
                qStartList.append(qStart)
                qEndList.append(qEnd)
                sStartList.append(sStart)
                sEndList.append(sEnd)
                evalList.append(evalue)
                bitScoreList.append(bitScore)
                qSeqList.append(qSeq)
                sSeqList.append(sSeq)
    df = pd.DataFrame({'queryAccVer':queryList,'subjectAccVer':subjectList, 'identity':percentIdentityList, 'alignmentLength':alignmentLenList,
                      'mismatches':mismatchList, 'gaps':gapList, 'qStart':qStartList,'qEnd':qEndList,'sStart':sStartList,'sEnd':sEndList,
                      'evalue':evalList, 'bitScore':bitScoreList,'qSeq':qSeqList, 'sSeq':sSeqList})
    return df, list(zip(qStartList, qEndList, sStartList, sEndList))

def trim_fully_contain(df, check_list):
    drop_index_list = []
    for l in check_list:
        qStart, qEnd, sStart, sEnd = l[0], l[1], l[2], l[3]
        sub_df = df[(df.qStart >= qStart) & (df.qEnd <= qEnd) & (df.sStart >= sStart) &(df.sEnd <= sEnd)]
        if sub_df.shape[0] > 1:
            sub_df = sub_df.sort_values(by=['alignmentLength'], ascending=False)
            overlap_index_list = list(sub_df.index.values)[1:]
            drop_index_list += overlap_index_list
    df = df.drop(df.index[drop_index_list]).reset_index(drop=True)
    return df

两个blast mapping：A，B；如果B完全是A的subsequence，drop B

In [3]:
df, check_list = parseBlastXML('temp_blastn/G000006925,G000299455.xml')
df = trim_fully_contain(df, check_list)

In [4]:
readyToGraphDf,G = MHG_partition.mhg(df)

2022-07-06 14:46:19,066 - root - INFO - start building dataframe containing pairwise blastn calls
2022-07-06 14:46:20,393 - root - INFO - start building an alignment graph
2022-07-06 14:46:20,825 - root - INFO - alignment graph finished building in time: 1.758699655532837
2022-07-06 14:46:20,825 - root - INFO - starting traversing the alignment graph and MHG partition
2022-07-06 14:46:20,879 - root - INFO - Total 125 cc are waiting to be visited
2022-07-06 14:46:21,737 - root - INFO - cc number 1 is on the show being visited
2022-07-06 14:46:21,737 - root - INFO - cc number 1 is a big cc, big but not that big, but still big; could take a few hours

node B ('G000299455', (4431865, 4470166)) (4458949, 4458987)
blockPath (4458949, 4458987)
leftBoundary 0
rightBoundary 0
subArrayBtoA
subArrayAtoB
directionAtoB == directionBtoA
pathAtoB (5557, 5595)
arrayAtoB ATTCAGCGCCTGATGCGACGCTGGCGCGTCTTATCAGGC 39
arrayAtoB count - 0

node B ('G000299455', (4431865, 4470166)) (4463350, 4463392)
blockPath (4463350, 4463392)

UnboundLocalError: local variable 'leftBoundary' referenced before assignment

In [23]:
display(df)
display(readyToGraphDf.sort_values(['alignmentLength'],ascending=False))

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
0,G000006925,G000299455,98.819,59509,676,27,2397883,2457367,1682614,1623109,0.00000,110276,CCGACTGGAATCACTGGATCGAAGTGAGCTGCGTAAACAGTTTTCC...,CCGACTGGAATCACTGGATCGAAGTGAGCTGCGTAAACAGTTTTCC...
1,G000006925,G000299455,98.836,58085,670,6,148899,206981,4293324,4235244,0.00000,107742,GGCGATGGGATTGATATTTATCTGCGGGAATTTATATTATGTTTCT...,GGCGATGGGATTGATATTTATCTGCGGGAATTTATATTATGTTTCT...
2,G000006925,G000299455,98.499,53966,777,33,3449767,3503727,488092,434155,0.00000,98973,GCCGCGAAGAGAAACAGCACTCCTGCGAGTAAAAAATCGGAACCTT...,GCCGCGAAGAGAAACAGCACTCCTGCGAGTAAAAAATCGGAACCTT...
3,G000006925,G000299455,98.710,45731,539,51,1122423,1168132,3103177,3057477,0.00000,84399,TTGTCAGCAATCCACTACAGGACATTATATGATCAGTTCATTATGG...,TTGTCACTAATCCACTACAGGACATTTTATGATCAGTTCATTATGG...
4,G000006925,G000299455,97.413,41009,991,70,3559547,3600494,376503,335504,0.00000,72612,CGCAGCAGCGTCGATTTCCCGCAGCCAGACGGCCCGACCATCACGA...,CGCAGCAGCGTCGATTTTCCGCAGCCAGACGGCCCGACCATCACGA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30190,G000006925,G000299455,86.486,37,5,0,4476815,4476851,5248465,5248429,3.01304,42,TGCCTGATGCGCTTCGCTTATCAGGCCTACAGCAGGC,TGCCTGATGCACTTCGCTAATCAGGCTTACCGTAGGC
30191,G000006925,G000299455,92.857,28,2,0,1607351,1607378,5295845,5295818,3.01304,42,ATTTGCAGCCGTCAGGCTGCCGTGGTTC,ATTTGCAGCCTCCAGGCTGCCGTGGTTC
30192,G000006925,G000299455,100.000,22,0,0,3714681,3714702,5299284,5299263,3.01304,42,TATTAAACGAGTTAATGATGTC,TATTAAACGAGTTAATGATGTC
30193,G000006925,G000299455,96.000,25,1,0,4818332,4818356,5326126,5326102,3.01304,42,GCCTTCCATGCCGCTGGCGCGGCAT,GCCTTCCATGCCGCTGTCGCGGCAT
30194,G000006925,G000299455,83.721,43,7,0,3069768,3069810,5330844,5330802,3.01304,42,CAGTGTTTTCATTGTAAACTGACGGTTTTCCCAGTCTTTCTGG,CAGTTTTTCCAGCGTAAACTGACGGGTTTCCCAGTCGCTCTGG

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,...,bitScore,qSeq,sSeq,qPair,sPair,qEdge,sEdge,sourceNode,destNode,align
13085,G000006925,G000299455,98.819,59509,676,27,2397883,2457367,1682614,1623109,...,110276,CCGACTGGAATCACTGGATCGAAGTGAGCTGCGTAAACAGTTTTCC...,CCGACTGGAATCACTGGATCGAAGTGAGCTGCGTAAACAGTTTTCC...,"(2397883, 2457367)","(1682614, 1623109)","((2397883, 2457367), CCGACTGGAATCACTGGATCGAAGT...","((1682614, 1623109), CCGACTGGAATCACTGGATCGAAGT...","(G000006925, (2374481, 2472008))","(G000299455, (1623109, 1682614))","(((G000006925, (2374481, 2472008)), (2397883, ..."
1057,G000006925,G000299455,98.836,58085,670,6,148899,206981,4293324,4235244,...,107742,GGCGATGGGATTGATATTTATCTGCGGGAATTTATATTATGTTTCT...,GGCGATGGGATTGATATTTATCTGCGGGAATTTATATTATGTTTCT...,"(148899, 206981)","(4293324, 4235244)","((148899, 206981), GGCGATGGGATTGATATTTATCTGCGG...","((4293324, 4235244), GGCGATGGGATTGATATTTATCTGC...","(G000006925, (64491, 216702))","(G000299455, (4235244, 4293324))","(((G000006925, (64491, 216702)), (148899, 2069..."
19862,G000006925,G000299455,98.499,53966,777,33,3449767,3503727,488092,434155,...,98973,GCCGCGAAGAGAAACAGCACTCCTGCGAGTAAAAAATCGGAACCTT...,GCCGCGAAGAGAAACAGCACTCCTGCGAGTAAAAAATCGGAACCTT...,"(3449767, 3503727)","(488092, 434155)","((3449767, 3503727), GCCGCGAAGAGAAACAGCACTCCTG...","((488092, 434155), GCCGCGAAGAGAAACAGCACTCCTGCG...","(G000006925, (3423912, 3503727))","(G000299455, (434155, 488092))","(((G000006925, (3423912, 3503727)), (3449767, ..."
7995,G000006925,G000299455,98.710,45731,539,51,1122423,1168132,3103177,3057477,...,84399,TTGTCAGCAATCCACTACAGGACATTATATGATCAGTTCATTATGG...,TTGTCACTAATCCACTACAGGACATTTTATGATCAGTTCATTATGG...,"(1122423, 1168132)","(3103177, 3057477)","((1122423, 1168132), TTGTCAGCAATCCACTACAGGACAT...","((3103177, 3057477), TTGTCACTAATCCACTACAGGACAT...","(G000006925, (1122423, 1168132))","(G000299455, (3057394, 3103258))","(((G000006925, (1122423, 1168132)), (1122423, ..."
20290,G000006925,G000299455,97.413,41009,991,70,3559547,3600494,376503,335504,...,72612,CGCAGCAGCGTCGATTTCCCGCAGCCAGACGGCCCGACCATCACGA...,CGCAGCAGCGTCGATTTTCCGCAGCCAGACGGCCCGACCATCACGA...,"(3559547, 3600494)","(376503, 335504)","((3559547, 3600494), CGCAGCAGCGTCGATTTCCCGCAGC...","((376503, 335504), CGCAGCAGCGTCGATTTTCCGCAGCCA...","(G000006925, (3559544, 3600494))","(G000299455, (335504, 377237))","(((G000006925, (3559544, 3600494)), (3559547, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16403,G000006925,G000299455,100.000,22,0,0,2980037,2980058,443221,443242,...,42,AAAAAGGCGCCGAAGCGCCTTT,AAAAAGGCGCCGAAGCGCCTTT,"(2980037, 2980058)","(443221, 443242)","((2980037, 2980058), AAAAAGGCGCCGAAGCGCCTTT)","((443221, 443242), AAAAAGGCGCCGAAGCGCCTTT)","(G000006925, (2976303, 3015537))","(G000299455, (434155, 488092))","(((G000006925, (2976303, 3015537)), (2980037, ..."
16394,G000006925,G000299455,100.000,22,0,0,2979965,2979986,146185,146164,...,42,CCCCTCACCCTAACCCTCTCCC,CCCCTCACCCTAACCCTCTCCC,"(2979965, 2979986)","(146185, 146164)","((2979965, 2979986), CCCCTCACCCTAACCCTCTCCC)","((146185, 146164), CCCCTCACCCTAACCCTCTCCC)","(G000006925, (2976303, 3015537))","(G000299455, (137973, 154383))","(((G000006925, (2976303, 3015537)), (2979965, ..."
28537,G000006925,G000299455,100.000,22,0,0,4572762,4572783,1538554,1538575,...,42,ATTGTCATTCTGATGGGATTAG,ATTGTCATTCTGATGGGATTAG,"(4572762, 4572783)","(1538554, 1538575)","((4572762, 4572783), ATTGTCATTCTGATGGGATTAG)","((1538554, 1538575), ATTGTCATTCTGATGGGATTAG)","(G000006925, (4557883, 4573403))","(G000299455, (1535847, 1550961))","(((G000006925, (4557883, 4573403)), (4572762, ..."
13782,G000006925,G000299455,100.000,22,0,0,2514252,2514273,3091941,3091920,...,42,GATAAGGCGTTTACGCCGCATC,GATAAGGCGTTTACGCCGCATC,"(2514252, 2514273)","(3091941, 3091920)","((2514252, 2514273), GATAAGGCGTTTACGCCGCATC)","((3091941, 3091920), GATAAGGCGTTTACGCCGCATC)","(G000006925, (2479150, 2517237))","(G000299455, (3057394, 3103258))","(((G000006925, (2479150, 2517237)), (2514252, ..."
20497,G000006925,G000299455,100.000,22,0,0,3568910,3568931,288345,288366,...,42,AAATTGCCTGATGCGCTACGCT,AAATTGCCTGATGCGCTACGCT,"(3568910, 3568931)","(288345, 288366)","((3568910, 3568931), AAATTGCCTGATGCGCTACGCT)","((288345, 288366), AAATTGCCTGATGCGCTACGCT)","(G000006925, (3559544, 3600494))","(G000299455, (288342, 302750))","(((G000006925, (3559544, 3600494)), (3568910, ..."

In [21]:
for cc in nx.strongly_connected_components(G):
    S = G.subgraph(cc)
    nodeList = list(S.nodes())
    edgeList = list(S.edges())
    numberOfNodes = len(nodeList)
    numberOfEdges = len(edgeList)
    print("number of Nodes:",numberOfNodes)
    print("number of Edges:",numberOfEdges)
    print("")

number of Nodes: 1479
number of Edges: 59624

number of Nodes: 37
number of Edges: 72

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 4
number of Edges: 6

number of Nodes: 3
number of Edges: 4

number of Nodes: 4
number of Edges: 6

number of Nodes: 12
number of Edges: 50

number of Nodes: 4
number of Edges: 6

number of Nodes: 3
number of Edges: 4

number of Nodes: 3
number of Edges: 4

number of Nodes: 6
number of Edges: 10

number of Nodes: 21
number of Edges: 44

number of Nodes: 3
number of Edges: 4

number of Nodes: 5
number of Edges: 10

number of Nodes: 5
number of Edges: 8

number of Nodes: 5
number of Edges: 12

number of Nodes: 5
number of Edges: 12

number of Nodes: 13
number of Edges: 44

number of Nodes: 9
number of Edges: 16

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 6
number of Edges: 16

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 5
number of Edges: 10

number of Nodes: 5
number of Edges: 8

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 3
number of Edges: 4

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 4

number of Nodes: 3
number of Edges: 4

number of Nodes: 10
number of Edges: 18

number of Nodes: 6
number of Edges: 12

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 14
number of Edges: 64

number of Nodes: 4
number of Edges: 8

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 3
number of Edges: 6

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 5
number of Edges: 8

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 8
number of Edges: 14

number of Nodes: 2
number of Edges: 2

number of Nodes: 6
number of Edges: 10

number of Nodes: 2
number of Edges: 2

number of Nodes: 4
number of Edges: 8

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 3
number of Edges: 4

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 4
number of Edges: 6

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 3
number of Edges: 4

number of Nodes: 5
number of Edges: 8

number of Nodes: 3
number of Edges: 4

number of Nodes: 2
number of Edges: 2

number of Nodes: 4
number of Edges: 6

number of Nodes: 3
number of Edges: 4

number of Nodes: 8
number of Edges: 20

number of Nodes: 4
number of Edges: 6

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 4
number of Edges: 6

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 4
number of Edges: 6

number of Nodes: 4
number of Edges: 6

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

number of Nodes: 2
number of Edges: 2

In [32]:
for l in check_list:
    qStart, qEnd, sStart, sEnd = l[0], l[1], l[2], l[3]
    sub_df = df[(df.qStart <= qStart) & (df.qEnd >= qStart)]
    if sub_df.shape[0] > 1:
        display(sub_df)

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
0,G000006925,G000299455,98.819,59509,676,27,2397883,2457367,1682614,1623109,0.0,110276,CCGACTGGAATCACTGGATCGAAGTGAGCTGCGTAAACAGTTTTCC...,CCGACTGGAATCACTGGATCGAAGTGAGCTGCGTAAACAGTTTTCC...
517,G000006925,G000299455,95.433,1489,52,16,2396403,2397891,1684258,1682786,0.0,2404,AGGGAAAGCAATTCTGACAGCGCCCCCTATACGTTATTAAAAAACT...,AGGGAAAGCAATTCTGACAGCGCCCCCTATACGTTATTAAAAAACT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
1,G000006925,G000299455,98.836,58085,670,6,148899,206981,4293324,4235244,0.0,107742,GGCGATGGGATTGATATTTATCTGCGGGAATTTATATTATGTTTCT...,GGCGATGGGATTGATATTTATCTGCGGGAATTTATATTATGTTTCT...
740,G000006925,G000299455,98.972,778,8,0,148126,148903,4589518,4588741,0.0,1450,TGTTGGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGAT...,TGTCGGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGAT...
1618,G000006925,G000299455,90.519,770,73,0,148130,148899,1581876,1582645,0.0,1060,GGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTA...,GGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTG...
1701,G000006925,G000299455,90.402,771,74,0,148129,148899,91526,92296,0.0,1056,TGGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTT...,TGGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTT...
2001,G000006925,G000299455,89.754,771,67,12,148129,148899,5323358,5324116,0.0,1008,TGGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTT...,TGGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
2,G000006925,G000299455,98.499,53966,777,33,3449767,3503727,488092,434155,0.0,98973,GCCGCGAAGAGAAACAGCACTCCTGCGAGTAAAAAATCGGAACCTT...,GCCGCGAAGAGAAACAGCACTCCTGCGAGTAAAAAATCGGAACCTT...
606,G000006925,G000299455,97.721,1009,23,0,3448765,3449773,489123,488115,0.0,1808,TCATCAGCAACGGCGCCATCTGGTCGCCCTGGAATAAACGTTGTGA...,TCACCAGCAACAGCGCCATCTGGTCACCCTGGAATAAACGTTGTGA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
4,G000006925,G000299455,97.413,41009,991,70,3559547,3600494,376503,335504,0.000000e+00,72612,CGCAGCAGCGTCGATTTCCCGCAGCCAGACGGCCCGACCATCACGA...,CGCAGCAGCGTCGATTTTCCGCAGCCAGACGGCCCGACCATCACGA...
9098,G000006925,G000299455,95.000,40,2,0,3559544,3559583,5248648,5248609,3.416360e-07,66,GTACGCAGCAGCGTCGATTTCCCGCAGCCAGACGGCCCGA,GTACGCAGCAGCGTCGATTTACCGCAGCCGGACGGCCCGA
27472,G000006925,G000299455,84.091,44,7,0,3559547,3559590,3540284,3540241,7.947270e-01,44,CGCAGCAGCGTCGATTTCCCGCAGCCAGACGGCCCGACCATCAC,CGCAGCAGGGTCGATTTACCGGAACCGGACGGCCCGATAATCAC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
6,G000006925,G000299455,99.065,37656,329,23,3362736,3400369,578411,540757,0.0,70332,CAACAATGTTCGGCATAATTATATCTGTCATCGTATTAATTACGAT...,CAACAATGTTCGGCATAATTATATCTGTCATCGTATTAATTACGAT...
1203,G000006925,G000299455,90.909,770,70,0,3361967,3362736,942497,941728,0.0,1077,AGGTAATGCTGCCAACTTATTGATTTAGTGTATGATGGTGATTTTA...,AGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTG...
1422,G000006925,G000299455,90.661,771,72,0,3361966,3362736,3679297,3680067,0.0,1067,AAGGTAATGCTGCCAACTTATTGATTTAGTGTATGATGGTGATTTT...,AAGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTT...
1472,G000006925,G000299455,90.637,769,72,0,3361968,3362736,696787,696019,0.0,1063,GGTAATGCTGCCAACTTATTGATTTAGTGTATGATGGTGATTTTAA...,GGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTGA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
12,G000006925,G000299455,98.723,27880,346,10,2976354,3004230,1016671,988799,0.000000e+00,51503,GCCTGATGCGACGCTGACGCGTCTTATCAG-GCCTACAAAGGCATA...,GCCTGATGCGACGCTGGCGCGTCTTATCAGTATCTACAAAGGCATA...
4184,G000006925,G000299455,88.636,88,10,0,2976305,2976392,4175049,4174962,4.392200e-21,112,CGTAGATCGGATAAGGCGTTCACGCCGCATCCGGCGGTTGCGCTCC...,CGTAGGCCGGATAAGGCGTTTACGCCGCATCCGGCACTTGTGCGCT...
4605,G000006925,G000299455,86.364,88,12,0,2976304,2976391,4476452,4476365,1.304370e-17,100,CCGTAGATCGGATAAGGCGTTCACGCCGCATCCGGCGGTTGCGCTC...,CCGTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCAGTCGGCGCA...
4840,G000006925,G000299455,87.342,79,10,0,2976312,2976390,4476544,4476466,7.108250e-16,94,CGGATAAGGCGTTCACGCCGCATCCGGCGGTTGCGCTCCGATGCCT...,CGGATAAGGCGTTCACACCGCATCCGGCAGTCGACGCACAATGCCT...
4919,G000006925,G000299455,87.209,86,10,1,2976304,2976389,4060380,4060296,2.694940e-15,92,CCGTAGATCGGATAAGGCGTTCACGCCGCATCCGGCGGTTGCGCTC...,CCGTAGGTCGGATAAGGCGCTCGCGCCGCATCCGAC-ACCATGCTC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28448,G000006925,G000299455,89.744,39,3,1,2976352,2976389,1491246,1491284,3.013040e+00,42,ATGCCTGATGCGACGC-TGACGCGTCTTATCAGGCCTAC,ATGCCGGATGCGACGCTTGCCGCGTCTTATCCGGCCTAC
28728,G000006925,G000299455,88.095,42,4,1,2976352,2976392,3322165,3322206,3.013040e+00,42,ATGCCTGATGCGACGCTG-ACGCGTCTTATCAGGCCTACAAA,ATGCCTGATGCGACGCTAAACGCGTCTTTTCAGGCGCACAAA
29096,G000006925,G000299455,86.486,37,5,0,2976354,2976390,5091662,5091698,3.013040e+00,42,GCCTGATGCGACGCTGACGCGTCTTATCAGGCCTACA,GCCGGATGCGACGCAAATGCGTCTTATCCGGCCTACA
29300,G000006925,G000299455,89.744,39,3,1,2976353,2976390,737005,736967,3.013040e+00,42,TGCCTGATGCGACGCT-GACGCGTCTTATCAGGCCTACA,TGCCGGATGCGACGCTTGACGCGCCTTATCCGGCCTACA
29356,G000006925,G000299455,86.486,37,5,0,2976353,2976389,972879,972843,3.013040e+00,42,TGCCTGATGCGACGCTGACGCGTCTTATCAGGCCTAC,TGCCGGATGCGATGCTGGCGCATCTTATCCGGCCTAC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
14,G000006925,G000299455,98.847,26976,311,0,87709,114684,4361035,4334060,0.0,50073,GGACATCAATATCCTTAAAGTAAATAAGACTATTCCTGACTATTAT...,GGACATCAATATCCTTAAAGTAAATAAGACTATTCCTGACTATTAT...
1668,G000006925,G000299455,90.507,769,73,0,86941,87709,1581877,1582645,0.0,1058,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...,GGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTGA...
1796,G000006925,G000299455,90.377,769,74,0,86941,87709,91528,92296,0.0,1052,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...,GGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTGA...
2031,G000006925,G000299455,89.727,769,67,12,86941,87709,5323360,5324116,0.0,1004,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...,GGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTGA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
19,G000006925,G000299455,98.622,24967,337,7,2288214,2313175,1790772,1765808,0.0,45991,CTGTTTTGCTTACTGCGGATTAAAGATGTTTAAGGCGCGGTCAGCA...,CTGTTTTGCTTACTGCGGATTAAAGATGTTTAAGGCGCGGTCAGCA...
835,G000006925,G000299455,98.960,769,8,0,2287446,2288214,4588746,4589514,0.0,1433,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...
1360,G000006925,G000299455,90.767,769,71,0,2287446,2288214,2062724,2061956,0.0,1069,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1431,G000006925,G000299455,90.815,773,70,1,2287446,2288218,4536647,4535876,0.0,1067,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1785,G000006925,G000299455,90.298,773,75,0,2287446,2288218,4593674,4592902,0.0,1054,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1897,G000006925,G000299455,90.247,769,75,0,2287446,2288214,1582644,1581876,0.0,1046,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1941,G000006925,G000299455,90.117,769,76,0,2287446,2288214,92295,91527,0.0,1040,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
2097,G000006925,G000299455,89.467,769,69,12,2287446,2288214,5324115,5323359,0.0,992,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
24,G000006925,G000299455,98.850,22879,258,5,41611,64488,4406324,4383450,0.0,42444,TTTCAATATTGGTGATTAAAGTTTTATTTCCAAATTAAAGGGCGTG...,TTTCAATATTGGTGATTAAAGTTTTATTTCCAAATTAAAGGGCGTG...
63,G000006925,G000299455,98.032,16413,319,4,25217,41626,4422836,4406425,0.0,29665,GCATCCGGCAAAAATCCTCAAAA-ATAAGAGCAAACCTGCATGTCT...,GCATCCGGCAAAAATCCTCAAAATATAAGAGCAAACCTGCATGTCT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
25,G000006925,G000299455,98.861,22394,251,4,1477846,1500238,2285471,2307861,0.0,41557,ATTGCACATGTCCAACAACATGCAGCTGCGCTTGAGGTCGAACTTT...,ATTGCCCATGTCCAACAGAATGCGGCTGTGCTTGAGGTCGAACTTT...
463,G000006925,G000299455,98.920,1851,20,0,1476005,1477855,2283537,2285387,0.0,3444,GTAAACTGAACGACGTCTCTTGCTAAAACACAGCAACTCTCATGCC...,GTAAACTGAACGACGTCTCTTGCTAAAACACAGCAACTCTCATGCC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
26,G000006925,G000299455,98.756,22432,253,26,986200,1008622,3384700,3362286,0.0,41425,ACGTATCGAACCATCAATGACTACGGGGCGGAAACGCCGCAACTCA...,ACGTATCGAACCATCAATGACTACGGGGCGGAAACGCCGCAACTCA...
1201,G000006925,G000299455,91.169,770,67,1,985431,986200,4536647,4535879,0.0,1079,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1467,G000006925,G000299455,90.649,770,72,0,985431,986200,4593674,4592905,0.0,1065,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1606,G000006925,G000299455,90.427,773,74,0,985428,986200,92298,91526,0.0,1060,TTCGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAA...,TTCGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAA...
1995,G000006925,G000299455,89.767,772,67,12,985429,986200,5324117,5323358,0.0,1010,TCGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAAT...,TCGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAAT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
27,G000006925,G000299455,98.721,22368,284,2,64575,86940,4383394,4361027,0.000000e+00,41338,AATGCCGGATGCGCTTTGCTTATCCGGCCTACAAAATCGCAGCGTG...,AATGCCGGATGCGCTTTGCTTATCCGGCCTACAAAATCGCAGCGTG...
5376,G000006925,G000299455,94.340,53,3,0,64535,64587,1936784,1936836,5.567960e-13,85,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCCTGATAAGACGCGTCAGCGTCGCATCAGGCACTGAATGCC...
5421,G000006925,G000299455,94.340,53,3,0,64535,64587,4854426,4854478,5.567960e-13,85,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCCTGATAAGACGCGACAGCGTCGCATCAGGCATTGATTGCC...
5916,G000006925,G000299455,97.727,44,1,0,64541,64584,4444941,4444984,3.034290e-11,79,CTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCCGGAT,CTGATAAGACGCGCCAGCGTCGCATCAGGCGCTGAATGCCGGAT
5965,G000006925,G000299455,92.453,53,4,0,64535,64587,956294,956242,3.034290e-11,79,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGTCTGATAAGACGCGCAAGCGTCGCATCAGACGTTGATTGCC...
6129,G000006925,G000299455,92.308,52,4,0,64535,64586,4636812,4636863,1.150390e-10,77,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCCTGATAAGACGCGACAGCGTCGCATCAGGCATTGATTACC...
6528,G000006925,G000299455,93.617,47,3,0,64541,64587,1016642,1016688,1.653550e-09,73,CTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCCGGATGCG,CTGATAAGACGCGCCAGCGTCGCATCAGGCGATAAATGCCTGATGCG
6551,G000006925,G000299455,90.566,53,5,0,64535,64587,1932179,1932231,1.653550e-09,73,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCCTGATAAGACGCGGCAGCGTCGCATCAGGCGCTGTTTGTC...
6934,G000006925,G000299455,80.315,127,18,7,64535,64656,1932091,1932215,6.269080e-09,71,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCCTGATAAGACGCGGCAGCGTCGCATCAGTCGCTGTTTGTC...
7336,G000006925,G000299455,93.333,45,3,0,64535,64579,1932267,1932311,2.376790e-08,69,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGC,GTAGGCCTGATAAGACGCGGCAGCGTCGCATCAGGCAATGAATGC
7527,G000006925,G000299455,88.889,54,6,0,64534,64587,632538,632485,2.376790e-08,69,CGTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGC...,CGTTGGCCTGATAAGACGCGCCAGCGTCACATCAGGCAATCCATGC...
7889,G000006925,G000299455,92.308,52,3,1,64535,64585,1170971,1171022,9.011090e-08,67,GTAGGCCTGATAAGACGCGCC-AGCGTCGCATCAGGCGTTGAATGC...,GTAGGCCTGATAAGACGCGTCAAGCGTCGCATCAGGCGCTGAATGT...
11061,G000006925,G000299455,86.792,53,7,0,64535,64587,3548885,3548833,4.910630e-06,62,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCCTGATAAGACGCGGTAGCGTCGCATCAGGCATCTGTTGCC...
13261,G000006925,G000299455,85.185,54,8,0,64534,64587,178962,178909,7.058480e-05,58,CGTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGC...,CGTAGGCATGATAAGACGCGTAAGCGTCGCATCAGGCAATGAATAC...
16789,G000006925,G000299455,84.615,52,8,0,64535,64586,1879211,1879160,1.014580e-03,54,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGCATGATAAGACGCTTCCGCGTCGCATCAGGCATAGGTTGCC...
21262,G000006925,G000299455,83.019,53,9,0,64535,64587,4661678,4661626,1.458340e-02,50,GTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAATGCC...,GTAGGGCGGATAAGATGCGCCAGCATCGCATCCGCCAATAAATGCC...
22963,G000006925,G000299455,86.047,43,6,0,64534,64576,3729108,3729066,5.528980e-02,48,CGTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCGTTGAA,CGTAGGTCGGATAAGACGCGGCAGCGTCGCATCCGACATTGAA
25325,G000006925,G000299455,90.909,33,3,0,64575,64607,5041554,5041522,2.096190e-01,46,AATGCCGGATGCGCTTTGCTTATCCGGCCTACA,AATGCCTGATGCGCTTCGCTTATCAGGCCTACA
26100,G000006925,G000299455,88.571,35,4,0,64575,64609,3527624,3527658,7.947270e-01,44,AATGCCGGATGCGCTTTGCTTATCCGGCCTACAAA,AATGCCTGATGCGCTACGCTTATCTGGCCTACAAA
26330,G000006925,G000299455,90.000,40,3,1,64537,64575,4463304,4463343,7.947270e-01,44,AGGCCTGATAAGACGC-GCCAGCGTCGCATCAGGCGTTGA,AGGCCTGATAAGACGCGGTAAGCGTCGCATCAGGCATTGA
29435,G000006925,G000299455,88.235,34,4,0,64575,64608,1404129,1404096,3.013040e+00,42,AATGCCGGATGCGCTTTGCTTATCCGGCCTACAA,AATGCCTGATGCGCTACGCTTATCAGGCCTACAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
29,G000006925,G000299455,98.654,21911,267,28,576627,598512,3650898,3672805,0.000000e+00,40379,TGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAAGT...,TGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAAGT...
2624,G000006925,G000299455,88.860,386,21,22,576335,576702,3650403,3650784,5.268090e-116,427,ATTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAA...,ATTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAA...
3257,G000006925,G000299455,87.791,172,16,5,576532,576702,3650313,3650480,3.928490e-36,162,GTCGTGCAGGATGACTCGACTTCGTCTCGCCCTTCGGCGCCGTTGC...,GTCGTGCAGGATGACTCG-CTTCG-CTTGCCCTACGG-GCCGTTGC...
3357,G000006925,G000299455,100.000,78,0,0,576625,576702,1530272,1530349,1.166670e-32,150,ATTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAA...,ATTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAA...
3360,G000006925,G000299455,100.000,78,0,0,576625,576702,3650072,3650149,1.166670e-32,150,ATTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAA...,ATTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAA...
3391,G000006925,G000299455,100.000,77,0,0,576627,576703,3650183,3650259,4.423170e-32,148,TGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAAGT...,TGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAAGT...
20498,G000006925,G000299455,78.873,71,15,0,576626,576696,1286255,1286185,1.458340e-02,50,TTGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAAG...,TTGGTGGCCCTTGCTGGACTTGAACCAGCGACCAAGCGATTATGAG...
21638,G000006925,G000299455,78.571,70,15,0,576627,576696,738754,738823,5.528980e-02,48,TGGTGGGTCGTGCAGGATTCGAACCTGCGACCAATTGATTAAAAGT...,TGGTGGCCCCTGCTGGACTTGAACCAGCGACCAAGCGATTATGAGT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
30,G000006925,G000299455,97.687,22354,496,21,2265102,2287445,1813107,1790765,0.0,39902,CCCACCAGCCCGTAAGCCAGCAGAATATCGCCGTCCCAGAACAATA...,CCCACCAGCCCGTAAGCCAGCAGAATATCGCCGTCCCAGAACAATA...
232,G000006925,G000299455,99.194,5834,47,0,2259276,2265109,1819014,1813181,0.0,10946,CGCATCCGGCAATATCCGCAATCACATCACTTCTTACGCGCGTATT...,CGCATCCGGCAATATCCACAATCACATCACTTCTTACGCGCGTATT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
33,G000006925,G000299455,98.614,20566,277,8,2771007,2791567,1274829,1254267,0.000000e+00,37860,TTCAGCTTACGCTTTTACTCTCATTTACGCTGCTGAGGCTGGTATA...,TTCAGCTTACGCTTTTACTCTCATTTACGCTGCTGAGGCTGGTATA...
3473,G000006925,G000299455,81.818,176,31,1,2770832,2771007,2004920,2005094,6.357800e-31,144,CGGTTCAAAGCTCTGCTGAACAATTGCGATCTTTTCCTGTGTGGTA...,CGGTACAAAACTCTGCTGAATAGCAGCGAT-TTTCCCAGCGTGGTG...
8785,G000006925,G000299455,90.741,54,3,2,2770966,2771017,5337207,5337260,3.416360e-07,66,TAAGTGATACTGGTTGTCTGGAGATTCAGGGGGCCAGTCTAT--TC...,TAAGTGATATTGGTTGTCTGGAGATTCTGGGGGCTAGTCTATCTTC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
35,G000006925,G000299455,98.800,20083,227,14,1445049,1465118,2243144,2263225,0.0,37185,TGATACGAGAAGCTTATAAATTTTTTCCAGATCGTCGATATTTCGA...,TGAAACGAGAAGCTTATAAATTTTTTCCAGATCGTCGATATTTCGA...
1262,G000006925,G000299455,90.791,771,71,0,1444280,1445050,941728,942498,0.0,1073,GGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...,GGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATG...
1627,G000006925,G000299455,90.519,770,73,0,1444280,1445049,3680067,3679298,0.0,1060,GGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...,GGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
38,G000006925,G000299455,98.940,19817,199,11,1637697,1657511,2525742,2505935,0.000000e+00,36862,TTTAAAGATCTTGGCCCGGAAGTCAGTTTCCGCCGTATTTATGAAT...,TTTAAAGATCTTGGCCCGGAAGTCAGTTTCCGCCGTATTTATGAAT...
2213,G000006925,G000299455,99.546,441,2,0,1637263,1637703,2586096,2585656,0.000000e+00,837,CAAAGCGCGTACCCACTCCAGCTACGGCAATATTGATGTGTTACAG...,CAAGGCGCGTACCCACTCCAGCTACGGCAATATTGATGTGTTACAG...
2469,G000006925,G000299455,80.100,799,159,0,1637504,1638302,3441977,3441179,6.965900e-174,619,GTCGATCACGGCGGCAGTATCAATATTCTGACCTCTCACCGCCCTT...,GTCGATAAGGGCGGTTGTATTAACGTACTGACCACTCAACGTCCGT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
39,G000006925,G000299455,98.059,20149,385,6,127988,148130,4320602,4300454,0.0,36466,CCTGGCGCTGCTCAGGCGAGGCGGACTGAATACGCTGGCGCGCCGC...,CCTGGCGCTGTTCGGGAGTTGCAGACTGAATACGCTCACGCGCTGC...
85,G000006925,G000299455,98.521,13390,186,12,114672,128049,4333834,4320445,0.0,24593,GTGACCGTTTTGCCACTGCCTGTAGGGCCAGTTACCAGCACCAGTC...,GTGACCGTTTTGCCGCTGCCTGTAGGGCCAGTTACCAGCACCAGTC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
41,G000006925,G000299455,98.411,19767,271,43,2326508,2346249,1752624,1732876,0.0,36128,CACATCATTACAACGCAATATCCGCCACTTCTTTTTGAACGGGTTG...,CACATCATTACAACGCAATATCCGCCACTTCTTTTTGAACGGGTTG...
91,G000006925,G000299455,98.703,13187,170,1,2313327,2326513,1765832,1752647,0.0,24359,TAGCCCGATGGCATCACCATCGGGCCTCTTTTTATTTACTCTCCTG...,TAGCCCGATGGCATCACCATCGGGCCTCTTTTTATTTACTCTCCTG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
42,G000006925,G000299455,99.016,19307,184,6,2617253,2636558,1430967,1411666,0.0,35968,TATTGAATCCGCAGCATGATGCCATAGTTCTTAACCAGCATTTCCA...,TATTGAATCCGCAGCATGATGCCATAGTTCTTAACCAGCATTTCCA...
611,G000006925,G000299455,99.365,945,5,1,2616312,2617255,2064113,2063169,0.0,1773,CAACAGCGTATTTTGCACAGGAGTCGCTGAAAAATACGCGTTAATC...,CAACAGCGTATTTTGCACAGGAGTCGCTGAAAAATACGCGTTAATC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
47,G000006925,G000299455,98.964,18527,191,1,3146257,3164783,800022,781497,0.000000e+00,34505,TTTACTTCGCTTTGGCGGTTTCTTCGCCGACCAGACCTATCTTCAG...,TTTATTTCGCTTTGGCGGTTTCTTCGCCGACCAGACCTATCTTCAG...
4503,G000006925,G000299455,83.929,112,17,1,3146148,3146259,988768,988658,3.440450e-18,102,ATGCCGGATGCGTCGTGAACGCCTTATCCGGCCTACAAACGCACGA...,ATGCCGGATGCGGCGTGAACGCCTTATCCGGCCTACAAAAACCTGC...
6759,G000006925,G000299455,79.464,112,22,1,3146148,3146259,3485633,3485523,1.653550e-09,73,ATGCCGGATGCGTCGTGAACGCCTTATCCGGCCTACAAACGCACGA...,ATGCCGGATGCGGCGTGTACGCCTTATCCGGCCTACAAAATCATGC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
48,G000006925,G000299455,97.528,19414,449,31,1366222,1385605,2837580,2818168,0.0,34491,CATTAGTAAACTGGAAAAATAATCCCGACGGCACGCGCAGTCCCTA...,CATTAGTAAACTGGAAAAATAATCCCGACGGTACACGCAGTCCGTA...
2021,G000006925,G000299455,89.481,770,68,13,1365466,1366222,942497,941728,0.0,1004,AGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTA...,AGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTG...
2093,G000006925,G000299455,89.221,770,70,13,1365466,1366222,3679298,3680067,0.0,992,AGGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTA...,AGGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTG...
2104,G000006925,G000299455,89.207,769,70,13,1365467,1366222,696787,696019,0.0,990,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...,GGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTGA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
50,G000006925,G000299455,99.571,17715,69,7,4191670,4209378,4970010,4952297,0.000000e+00,33593,AACTGCCAGGCATCAAATTAAGCAGAAAGCC---CAGTCG---GGC...,AACTGCCAGGCATCAAATTAAGCAGAAGGCCATCCTGACGGATGGC...
326,G000006925,G000299455,99.470,3397,16,2,4188297,4191692,1329940,1333335,0.000000e+00,6409,GTCCCCTTCGTCTAGAGGCCCAGGACACCGCCCTTTCACGGCGGTA...,GTCCCCTTCGTCTAGAGGCCCAGGACACCGCCCTTTCACGGCGGTA...
336,G000006925,G000299455,99.387,3265,18,2,4188444,4191707,5110614,5107351,0.000000e+00,6143,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
337,G000006925,G000299455,99.417,3257,18,1,4188444,4191700,5208052,5204797,0.000000e+00,6143,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
346,G000006925,G000299455,99.446,3251,15,3,4188444,4191692,526647,529896,0.000000e+00,6118,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
348,G000006925,G000299455,99.203,3264,25,1,4188444,4191707,4931930,4928668,0.000000e+00,6116,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
352,G000006925,G000299455,99.324,3254,20,2,4188444,4191696,4224413,4221161,0.000000e+00,6110,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
360,G000006925,G000299455,99.173,3264,25,2,4188444,4191706,4973404,4970142,0.000000e+00,6101,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
3008,G000006925,G000299455,94.040,151,9,0,4191557,4191707,530006,530156,2.771760e-59,239,AGAATTAGCCTGGCGGCCGTAGCGCGGTGGTCCCACCTGACCCCAT...,AGAATTTGTCTGGCGGCAGTAGCGCGGTGGTCCCACCTGACCCCAT...
16984,G000006925,G000299455,96.774,31,1,0,4191670,4191700,4221048,4221018,1.014580e-03,54,AACTGCCAGGCATCAAATTAAGCAGAAAGCC,AACTGCCAGGCATCAAATTAAGCAGTAAGCC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
52,G000006925,G000299455,98.895,17470,192,1,4497401,4514869,4705975,4688506,0.000000e+00,32467,GCGGGAATAGCTCAGTTGGTAGAGCACGACCTTGCCAAGGTCGGGG...,GCGGGAATAGCTCAGTTGGTAGAGCACGACCTTGCCAAGGTCGGGG...
3434,G000006925,G000299455,100.000,76,0,0,4497401,4497476,2108755,2108830,1.676950e-31,146,GCGGGAATAGCTCAGTTGGTAGAGCACGACCTTGCCAAGGTCGGGG...,GCGGGAATAGCTCAGTTGGTAGAGCACGACCTTGCCAAGGTCGGGG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
56,G000006925,G000299455,98.852,17334,191,8,808517,825842,3520974,3503641,0.000000e+00,32151,CGTCTTATCAGGCTTGGAGGTGGCAATTACTGCCCGCACACCTCAC...,CGTCTTATCAGGCCTGGAGGTGGCAATTACTGCCCGCACACCTCAC...
5643,G000006925,G000299455,85.057,87,12,1,808450,808535,4463386,4463300,2.110970e-12,83,GTAGGCCAGATAAGGCGTTCACGCCGCATCTGGCGTCTGGAGC-AA...,GTAGGCCGGAAAAGGCGTTCACGCCGTATCCGGCATTCGGTGCTCA...
5811,G000006925,G000299455,87.059,85,9,2,808443,808526,4476457,4476374,8.003310e-12,81,CCGAACCGTAGGCCAGATAAGGCGTTCACGCCGCATCTGGCGTCTG...,CCGAACCGTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCAGTCG...
6016,G000006925,G000299455,87.654,81,8,2,808450,808529,4038374,4038295,3.034290e-11,79,GTAGGCCAGATAAGGCGTTCACGCCGCATCTGGC-GTCTGGAGCAA...,GTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCAGTCGTGCGC-C...
6021,G000006925,G000299455,83.750,80,13,0,808450,808529,4338696,4338617,3.034290e-11,79,GTAGGCCAGATAAGGCGTTCACGCCGCATCTGGCGTCTGGAGCAAA...,GTAGGTCGGATAAGGCGTTCACGCCGCATCCGACATTTGCACAAGA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29450,G000006925,G000299455,88.235,34,4,0,808496,808529,1440802,1440769,3.013040e+00,42,TGCCTGATGCGACGCTTGTCGCGTCTTATCAGGC,TGCCGGATGCGACGCTTGCCACGTCTTATCCGGC
29591,G000006925,G000299455,93.939,33,1,1,808497,808529,1932214,1932183,3.013040e+00,42,GCCTGATGCGACGCTTGTCGCGTCTTATCAGGC,GCCTGATGCGACGCT-GCCGCGTCTTATCAGGC
29681,G000006925,G000299455,88.235,34,4,0,808496,808529,2799159,2799126,3.013040e+00,42,TGCCTGATGCGACGCTTGTCGCGTCTTATCAGGC,TGCCGGATGCGACGCTGGCCGCGTCTTATCCGGC
29976,G000006925,G000299455,88.235,34,4,0,808496,808529,4398293,4398260,3.013040e+00,42,TGCCTGATGCGACGCTTGTCGCGTCTTATCAGGC,TGCCGGATGCGACGCCGGTCGCGTCTTATCCGGC
30238,G000006925,G000299455,93.939,33,1,1,808497,808529,5120494,5120463,3.013040e+00,42,GCCTGATGCGACGCTTGTCGCGTCTTATCAGGC,GCCTGATGCGACGCTGG-CGCGTCTTATCAGGC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
57,G000006925,G000299455,98.559,17285,234,15,1427009,1444280,2225870,2243152,0.000000e+00,31769,GTTTATGAATGGCAAAAGGACGTTGATTTGCATCAGGTCTTGTGGA...,GTTTATGAATGGCAAAAGGACGTTGATTTGCATCAGGTCTTGTGGA...
680,G000006925,G000299455,99.274,827,6,0,1426183,1427009,3183049,3182223,0.000000e+00,1556,TACAACTGGGTACAGCATGAACCCTCAGACAGAAAACAAAGTGATG...,TACAACTGGGTACAGCATGAACCCTCAGACAGAAAACAAAGTGATG...
2642,G000006925,G000299455,100.000,217,0,0,1426793,1427009,4741347,4741563,4.126550e-113,417,GAACGCTGAAAAATGAGAGCCTGAGCCACTATCGTTTTAATAACCG...,GAACGCTGAAAAATGAGAGCCTGAGCCACTATCGTTTTAATAACCG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
58,G000006925,G000299455,98.930,16820,178,2,2791971,2808788,1253880,1237061,0.000000e+00,31282,ATGGTGCATCCGGGAGGATTCGAACCTCCGACCGCTCGGTTCGTAG...,ATGGTGCATCCGGGAGGATTCGAACCTCCGACCGCTCGGTTCGTAG...
3002,G000006925,G000299455,94.444,162,6,3,2791830,2791990,1254153,1253994,7.310870e-60,241,ATGGTGCATCCGGGAGGATTCGAACCTCCGACCGCTCGGTTCGTAG...,ATGGTGCATCCGGGAGGATTCGAACCTCCGACCGCTCGGTTCGTAG...
3346,G000006925,G000299455,100.000,79,0,0,2791971,2792049,1254153,1254075,3.077230e-33,152,ATGGTGCATCCGGGAGGATTCGAACCTCCGACCGCTCGGTTCGTAG...,ATGGTGCATCCGGGAGGATTCGAACCTCCGACCGCTCGGTTCGTAG...
29402,G000006925,G000299455,100.000,22,0,0,2791969,2791990,1254288,1254267,3.013040e+00,42,AGATGGTGCATCCGGGAGGATT,AGATGGTGCATCCGGGAGGATT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
60,G000006925,G000299455,98.672,16420,210,8,1551772,1568190,2393953,2410365,0.000000,30284,GGCCGCTATGCGGCCTTTTTTCTTTTCACTGTCGAAGAGTCACCGT...,GGCCGCTCTGCGGCCTTTTTTCTTTTCACTGTCGAAGAGTCACCGT...
173,G000006925,G000299455,99.165,8263,68,1,1543535,1551796,2347900,2356162,0.000000,15480,CTGTTCCTGTTCAATATAATCCAGTATGCTTCGCAAATGGTTAGCT...,CTGTTCCTGTTCAATATAATCCAGTATGCTTCGCAAATGGTTAGCT...
23387,G000006925,G000299455,100.000,24,0,0,1551767,1551790,617596,617619,0.209619,46,AAAAAGGCCGCTATGCGGCCTTTT,AAAAAGGCCGCTATGCGGCCTTTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
64,G000006925,G000299455,98.820,16013,174,15,4050255,4066253,5110614,5094603,0.0,29640,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
322,G000006925,G000299455,99.220,3462,22,5,4050108,4053565,1329940,1333400,0.0,6472,GTCCCCTTCGTCTAGAGGCCCAGGACACCGCCCTTTCACGGCGGTA...,GTCCCCTTCGTCTAGAGGCCCAGGACACCGCCCTTTCACGGCGGTA...
338,G000006925,G000299455,99.446,3249,17,1,4050255,4053503,5208052,5204805,0.0,6134,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
343,G000006925,G000299455,99.446,3252,15,3,4050255,4053504,526647,529897,0.0,6120,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
351,G000006925,G000299455,99.294,3258,21,2,4050255,4053511,4973404,4970148,0.0,6112,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
354,G000006925,G000299455,99.384,3247,18,2,4050255,4053500,4224413,4221168,0.0,6109,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...
359,G000006925,G000299455,98.650,3333,40,5,4050255,4053584,4931930,4928600,0.0,6101,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...,TTTGCTCTTTAAAAATCTGGATCAAGCTGAAAATTGAAACACTGAA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
66,G000006925,G000299455,99.016,15352,151,0,3762617,3777968,137079,121728,0.0,28646,GCCTGTGAGATATTATTTTTACAGGTGAGAGAGTCACTTCAGGGTA...,GCCTGTGAGATATTATTTTTACAGGTGAGAGAGTCACTTCAGGGTA...
1225,G000006925,G000299455,90.803,772,71,0,3761849,3762620,2062724,2061953,0.0,1075,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
68,G000006925,G000299455,98.114,15484,280,12,3746366,3761848,153445,137973,0.000000,28058,CCAACACCACCAATATCACCAACCTGACGGATTCCGTTGGTGACCT...,CCAATACCACCAATATCACCAACCTGACGGATTCCGTTGGTGACCT...
657,G000006925,G000299455,99.552,893,3,1,3745490,3746382,154383,153492,0.000000,1684,AAACGCCATTGCCCTGGGGCGTAGCAGTGTAGCTAGCGGTACTGAC...,AAACGCAATTGCCCTGGGGCGTAGCAGTGTAGCTAGCGGTACTGAC...
26702,G000006925,G000299455,77.465,71,16,0,3746317,3746387,153281,153211,0.794727,44,GATGCGGTTAACGGTTCCCAACTGAAAGCTACCAATGACGATGTCG...,GATGCTGTTAACGGCTCTCAGCTGAAAACCACCAACGATGCTGTGG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
70,G000006925,G000299455,98.987,14902,144,7,2711449,2726348,1344983,1330087,0.0,27723,AATGCCGGGTTTAAGCCCGGCATTGTTTTTTTACGCAACCACAAAA...,AATGCCGGGTTTAATCCCGACATT--ATTTTTATCCAGCCACAAAA...
74,G000006925,G000299455,98.834,14586,169,1,2696888,2711472,1359721,1345136,0.0,27054,TAATTACTAAACGCTGTATTAATTGTGATATGTGTGAACCCGAATG...,TAATCACTAAAAAATGCATCAATTGTGATATGTGTGAACCCGAATG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
71,G000006925,G000299455,98.990,14858,146,4,3307755,3322611,630216,615362,0.0,27673,CTTTTTCCGCAGCTTCACGTTTCGCTTGTTCAGCAGCTTCACGCTT...,CTTGTTCAGCAGCTTCACGCTTAGCTTGTTCTGCGGCCTCACGTTC...
104,G000006925,G000299455,98.863,12309,140,0,3295580,3307888,642415,630107,0.0,22859,AGCTCACTTTGTTAACAACTTTAACTATTCTTTAATGCAGTATTAA...,AGCTCACTTTGTTAACAACTTTAACTACTCTTTAATGCAGTATTAA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
23,G000006925,G000299455,98.866,23019,230,31,2479150,2502138,1574182,1551165,0.0,42715,ATACTTTGGCTGACATTTTTTTCCCTTAAATTCATCTGAGTTACGC...,ATACTTTGGCTGACATTTTTTTCCCTTAAATTCATCTGAGTTACGC...
72,G000006925,G000299455,98.372,15109,244,2,2502131,2517237,1550961,1535853,0.0,27622,GCTGGCGCTGGATATCGCCAACAAAACGCTACCGCTGTTTCGCCAT...,GCTGGCGCTGGATATCGCCAACAAAACGCTACCTCTGTTTCGCCAT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
76,G000006925,G000299455,98.421,14438,212,16,3246818,3261241,694069,679634,0.000000e+00,26406,ATCCGGCACAATACTCAAAACCTGGCGTTTATCTGGCCTTGCTCGC...,ATCCGGCACAATACCCAAAACCTGGCGTTTATCTGGCCTTGCTCGC...
6893,G000006925,G000299455,97.500,40,1,0,3246786,3246825,972840,972879,6.269080e-09,71,CCCGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGCA,CCCGTAGGCCGGATAAGATGCGCCAGCATCGCATCCGGCA
7069,G000006925,G000299455,97.500,40,1,0,3246785,3246824,264418,264379,6.269080e-09,71,CCCCGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGC,CCCCGTAGGCCGGATAAGATGCGCCAGCATCGCATCCGGC
8156,G000006925,G000299455,97.368,38,1,0,3246787,3246824,463865,463828,9.011090e-08,67,CCGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGC,CCGTAGGCCGGATAAGATGCGCCAGCATCGCATCCGGC
12042,G000006925,G000299455,90.698,43,4,0,3246783,3246825,736957,736915,1.861760e-05,60,CACCCCGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGCA,CACCCCGCAGGCCTGATAAGATGCGCCAGCATCGCATCAGGCA
12197,G000006925,G000299455,94.595,37,2,0,3246789,3246825,2825987,2825951,1.861760e-05,60,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGCA,GTAGGCCGGATAAGATGCGCTAGCATCGCATCCGGCA
17095,G000006925,G000299455,94.118,34,2,0,3246789,3246822,4661678,4661645,1.014580e-03,54,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,GTAGGGCGGATAAGATGCGCCAGCATCGCATCCG
19059,G000006925,G000299455,91.667,36,3,0,3246791,3246826,5188929,5188894,3.846550e-03,52,AGGCCGGATAAGGTGCGCCAGCATCGCATCCGGCAC,AGGCCGGAAAAGATGCGTCAGCATCGCATCCGGCAC
19302,G000006925,G000299455,89.474,38,4,0,3246785,3246822,1236974,1237011,1.458340e-02,50,CCCCGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,CCCCGTAGGTCGGATAAGACGCGCCAGCGTCGCATCCG
19740,G000006925,G000299455,91.429,35,3,0,3246788,3246822,3625911,3625945,1.458340e-02,50,CGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,CGTAGGTCGGATAAGATGCGCAAGCATCGCATCCG
21762,G000006925,G000299455,89.189,37,4,0,3246789,3246825,1477872,1477908,5.528980e-02,48,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGCA,GTAGGCCGGATAAGACGCGTCAGCGTCGCATCCGGCA
22067,G000006925,G000299455,91.176,34,3,0,3246789,3246822,3625819,3625852,5.528980e-02,48,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,GTAGGTCGGATAAGATGCGCAAGCATCGCATCCG
22774,G000006925,G000299455,91.176,34,3,0,3246789,3246822,1921579,1921546,5.528980e-02,48,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,GTAGGTCGGATAAGATGCGTCAGCATCGCATCCG
24653,G000006925,G000299455,90.244,41,3,1,3246786,3246825,1491387,1491347,2.096190e-01,46,CCCGTAGGCCGGATAAGGTGCG-CCAGCATCGCATCCGGCA,CCCGTAGGCCGGATAAGACGCGGCAAGCATCGCATCCGGCA
25443,G000006925,G000299455,86.842,38,5,0,3246788,3246825,229632,229669,7.947270e-01,44,CGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCGGCA,CGTAGGCCTGATAAGACGCGCCAGCGTCGCATCAGGCA
25651,G000006925,G000299455,86.842,38,5,0,3246785,3246822,1237072,1237109,7.947270e-01,44,CCCCGTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,CCCCGTAGGTTGGATAAGACGCGCCAGCGTCGCATCCG
28485,G000006925,G000299455,88.235,34,4,0,3246789,3246822,1631995,1632028,3.013040e+00,42,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,GTAGGTCGGATAAGACGCGCCAGCGTCGCATCCG
29794,G000006925,G000299455,88.235,34,4,0,3246793,3246826,3448048,3448015,3.013040e+00,42,GCCGGATAAGGTGCGCCAGCATCGCATCCGGCAC,GCCGGATAAGGCGCGGTAGCGTCGCATCCGGCAC
30180,G000006925,G000299455,88.235,34,4,0,3246789,3246822,4991382,4991349,3.013040e+00,42,GTAGGCCGGATAAGGTGCGCCAGCATCGCATCCG,GTAGGTCGGATAAGATGCGCAAGTATCGCATCCG

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
77,G000006925,G000299455,98.245,14470,253,1,3022228,3036697,970820,956352,0.0,26347,TCATCTTCAAGATAAGTATAACCGTACAAACCTGCCTCGAACTCTT...,TCATCTTCAAGATAGGTATAACCGTACAAACCTGCCTCGAACTCTT...
873,G000006925,G000299455,98.953,764,8,0,3021465,3022228,4588746,4589509,0.0,1423,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...
985,G000006925,G000299455,97.906,764,16,0,3021465,3022228,3183050,3183813,0.0,1377,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTGATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1363,G000006925,G000299455,90.862,766,70,0,3021465,3022230,2062724,2061959,0.0,1069,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1446,G000006925,G000299455,90.743,767,71,0,3021464,3022230,941728,942494,0.0,1065,GGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...,GGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATG...
1460,G000006925,G000299455,90.992,766,68,1,3021465,3022230,4536647,4535883,0.0,1065,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1712,G000006925,G000299455,90.310,774,75,0,3021464,3022237,696019,696792,0.0,1056,GGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...,GGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATG...
1744,G000006925,G000299455,90.402,771,74,0,3021464,3022234,3680067,3679297,0.0,1056,GGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...,GGGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATG...
1822,G000006925,G000299455,90.470,766,73,0,3021465,3022230,4593674,4592909,0.0,1052,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1902,G000006925,G000299455,90.339,766,74,0,3021465,3022230,1582644,1581879,0.0,1046,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
1946,G000006925,G000299455,90.209,766,75,0,3021465,3022230,92295,91530,0.0,1040,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...
2103,G000006925,G000299455,89.556,766,68,12,3021465,3022230,5324115,5323362,0.0,992,GGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATGC...,GGTAATGACTCCAACTTATTGATAGTGTTTTATGTTCAGATAATGC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
79,G000006925,G000299455,99.116,13907,123,0,3703948,3717854,211581,197675,0.0,26030,AAAAAAGCCTGCCAGATGGCAGGCTTTTTAATAACGGCGTTATTAC...,AAAAAAGCCTGCCAGATGGCAGGCTTTTTAATAACGGCGTTATTAC...
759,G000006925,G000299455,99.220,769,6,0,3703180,3703948,4589513,4588745,0.0,1444,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...
1392,G000006925,G000299455,90.767,769,71,0,3703180,3703948,4592907,4593675,0.0,1069,GGTAATGCTGCCAACTTACTGATTTAGTGTATGATGGTGATTTTAA...,GGTGATGCTGCCAACTTACTGATTTAGTGTATGATGGTGTTTTTGA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
80,G000006925,G000299455,98.484,14052,211,2,445103,459153,3907703,3893653,0.000000e+00,25770,CGTAGGCCGGATAAGGCGTTTACGCCGCATCCGGCAGTCATGCGTC...,CGTAGGCCGGATAAGGCGTTTACGCCGCATCCGGCAGTCATGCGTC...
3210,G000006925,G000299455,88.652,141,15,1,445001,445141,4476552,4476413,1.901420e-38,169,TCGTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCATCCGAGCAC...,TCGTAAGCCGGATAAGGCGTTCACACCGCATCCGGCAGTCGACGCA...
3418,G000006925,G000299455,85.821,134,19,0,445002,445135,4175049,4174916,4.423170e-32,148,CGTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCATCCGAGCACC...,CGTAGGCCGGATAAGGCGTTTACGCCGCATCCGGCACTTGTGCGCT...
3664,G000006925,G000299455,89.781,137,9,5,445003,445138,4923821,4923689,4.980130e-28,135,GTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCA-TCCGAGCACC...,GTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCAATCGGTGCACG...
3731,G000006925,G000299455,89.130,138,10,5,445002,445138,4923724,4923591,7.158370e-27,131,CGTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCA-TCCGAGCAC...,CGTAGGCCGGATAAGGCATTTACGCCGCATCCGGCAATCGGTGCAC...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23631,G000006925,G000299455,90.909,33,3,0,445103,445135,1461090,1461122,2.096190e-01,46,CGTAGGCCGGATAAGGCGTTTACGCCGCATCCG,CGTAGTTCGGATAAGGCGTTCACGCCGCATCCG
24774,G000006925,G000299455,92.105,38,2,1,445099,445135,1936760,1936723,2.096190e-01,46,GAACCGTAGGCCGGATAAGGCGTTT-ACGCCGCATCCG,GAACCGTAGGATGGATAAGGCGTTTTACGCCGCATCCG
28193,G000006925,G000299455,90.323,31,3,0,445103,445133,298504,298534,3.013040e+00,42,CGTAGGCCGGATAAGGCGTTTACGCCGCATC,CGTAGGCCAGATAAGGGGTTTACGCTGCATC
29366,G000006925,G000299455,90.323,31,3,0,445103,445133,972945,972915,3.013040e+00,42,CGTAGGCCGGATAAGGCGTTTACGCCGCATC,CGTAGGTCAGATAAGGCGTTCACGCCGCATC
29836,G000006925,G000299455,85.000,40,6,0,445099,445138,3639492,3639453,3.013040e+00,42,GAACCGTAGGCCGGATAAGGCGTTTACGCCGCATCCGGCA,GAACCGTTGGCCGGAGAGGGCGCTTAGGCCGCCTCCGGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
81,G000006925,G000299455,97.663,14423,331,6,2017917,2032333,2082711,2068289,0.0,25768,GGCGGAAGAACAGCTCAAAATGTTGATCGATTATCAGAATGAATAT...,GGCGGAAGAACAGCTCAAAATGCTGATCGATTATCAGAATGAATAT...
190,G000006925,G000299455,98.036,7789,136,17,2010142,2017923,2090582,2082804,0.0,14036,TTAACGTATCAATTAGATTTAATAACAACGATATCCGTACCTAACC...,TTAACGTATCAACTAGATTTAATAACAACGATATCCGCACCTAACC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
47,G000006925,G000299455,98.964,18527,191,1,3146257,3164783,800022,781497,0.0,34505,TTTACTTCGCTTTGGCGGTTTCTTCGCCGACCAGACCTATCTTCAG...,TTTATTTCGCTTTGGCGGTTTCTTCGCCGACCAGACCTATCTTCAG...
82,G000006925,G000299455,98.653,13657,184,0,3164776,3178432,781429,767773,0.0,25197,GGATAACGGCCCCGGTGTGACACCAGAGGCACTGGCGCGAATTGGC...,GGATAACGGCCCCGGTGTGACGCCAGAGGCTCTGGCGCGAATTGGC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
14,G000006925,G000299455,98.847,26976,311,0,87709,114684,4361035,4334060,0.0,50073,GGACATCAATATCCTTAAAGTAAATAAGACTATTCCTGACTATTAT...,GGACATCAATATCCTTAAAGTAAATAAGACTATTCCTGACTATTAT...
85,G000006925,G000299455,98.521,13390,186,12,114672,128049,4333834,4320445,0.0,24593,GTGACCGTTTTGCCACTGCCTGTAGGGCCAGTTACCAGCACCAGTC...,GTGACCGTTTTGCCGCTGCCTGTAGGGCCAGTTACCAGCACCAGTC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
86,G000006925,G000299455,99.423,12989,74,1,4117668,4130655,5047437,5034449,0.000000e+00,24532,TAATCCCCACAGCCGGATGAACTAACGTTCGTCCGGTTTGCTATTG...,TAATCCCCACAGCCGGATGAACTAACGTTCGTCCGGTTTGCTATTG...
3590,G000006925,G000299455,81.143,175,32,1,4117495,4117669,2004920,2005093,1.313570e-28,137,CGGTTCAAAGCTCTGCTGAACAATTGCGATCTTTTCCTGTGTGGTA...,CGGTACAAAACTCTGCTGAATAGCAGCGAT-TTTCCCAGCGTGGTG...
10750,G000006925,G000299455,92.683,41,3,0,4117629,4117669,5337207,5337247,4.910630e-06,62,TAAGTGATACTGGTTGTCTGGAGATTCAGGGGGCCAGTCTA,TAAGTGATATTGGTTGTCTGGAGATTCTGGGGGCTAGTCTA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
88,G000006925,G000299455,98.811,13202,144,13,4416674,4429862,4626810,4640011,0.000000e+00,24459,CTACGTGATTCCTGCAATTTATTGAATTTGTAGGCCGGATTGGGCG...,CTACGTGATTCCTGCAATTTATTGAATTTGTTGGCCGGATAAGGCA...
258,G000006925,G000299455,97.019,5603,166,1,4411073,4416675,4619931,4625532,0.000000e+00,9800,CCTGCGAATCATTTAACTCCTGTATATTATTTAACTTCTGATGATT...,CCTGCGAGTTATTCAAGTCCTGAGAATTATTTAACTCCTGCGGAAT...
4017,G000006925,G000299455,81.633,147,17,10,4416631,4416767,5041569,5041423,8.059750e-23,117,GATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTA...,GATGACAGAAGCAAAAATGCCTGATGCGCTTCGCTTATCAGGCCTA...
4064,G000006925,G000299455,80.380,158,22,9,4416625,4416773,3571623,3571466,3.055680e-22,116,AAGTCTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCA...,AAGACTGATGACAAACGGAAAACAGCCTGATGTGCTACGCTTATCA...
4169,G000006925,G000299455,82.576,132,13,10,4416636,4416757,1345124,1344993,4.392200e-21,112,CAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGA...,CAAACGCAAAACTGCCTGATGCGCTACGCTTATCAGGCCTACGTGG...
4298,G000006925,G000299455,81.333,150,16,12,4416629,4416767,3816015,3815867,6.313280e-20,108,CTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCC...,CTGATGACAAACGCTAAACTGCCTGATGCGCTACGCTTATCAGGCC...
4387,G000006925,G000299455,81.102,127,24,0,4416642,4416768,5094699,5094573,2.393550e-19,106,CAAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTG...,CAAGATTGCCTGATGCGCTACGCTTATCAGGCCTACAAAACCTGTT...
4578,G000006925,G000299455,82.500,120,11,10,4416643,4416752,192910,192791,1.304370e-17,100,AAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTGC...,AAAATTGCCTGATGCGCTACGCTTATCAGGCCTACATGATTTTTGC...
4625,G000006925,G000299455,82.308,130,12,11,4416636,4416755,988656,988784,4.945260e-17,98,CAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGA...,CAAAAGCAAAATTGCCTGATGCGCTACGCTTATCAGGCCTACACGT...
4675,G000006925,G000299455,81.618,136,14,11,4416614,4416738,3554217,3554082,4.945260e-17,98,ATGCCCGGATTAAGTCTGATGA-CAAAAGCAAAATCGCCCGATGCG...,ATGCCCGGCATCAGGCTGATGAACAAACGCAAAACTGCCTGATGCG...
4725,G000006925,G000299455,81.102,127,14,10,4416649,4416765,4689307,4689433,1.874890e-16,96,GCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTGCAATTTA...,GCCTGATGCACTACGTTTATCCGGCCTACATGATCTCTGCAATATA...
4872,G000006925,G000299455,77.640,161,26,10,4416622,4416772,3485507,3485667,2.694940e-15,92,ATTAAGTCTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTA...,ATTGAGACTGATGACAAAAGTAAGATTGCCTGATGCGCTGCGCTTA...
5044,G000006925,G000299455,79.412,136,18,10,4416643,4416768,3987468,3987333,1.021730e-14,91,AAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTGC...,AAAATTGCCTGATGCGCTACGCTTATCAGGACTACGTTATTTCAGC...
5212,G000006925,G000299455,78.571,140,20,10,4416636,4416765,3926215,3926354,1.468620e-13,87,CAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGA...,CAAACGCAAAACTGCCTGATGCGCTACGCTTATCAGGCCTACACCG...
6190,G000006925,G000299455,90.909,55,5,0,4416649,4416703,3124461,3124407,1.150390e-10,77,GCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTGCAATTTA...,GCCTGATGCGCTACGCTTATCAGGCCTACATCGTTCCTGCAATTTA...
6519,G000006925,G000299455,77.692,130,20,9,4416624,4416744,697324,697453,1.653550e-09,73,TAAGTCTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATC...,TAAGACTGATGACAAGCGCAAAATCGCCAGATGCGCTACGCTTATC...
6761,G000006925,G000299455,93.617,47,3,0,4416629,4416675,3529018,3528972,1.653550e-09,73,CTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT,CTGATGACAAATGCAAAATAGCCTGATGCGCTACGCTTATCAGGCCT
7824,G000006925,G000299455,79.612,103,11,10,4416649,4416741,6079,6181,9.011090e-08,67,GCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTGCAATTTA...,GCCTGATGCGCTACGCTTATTAGTCCTACGAGACTCCTGCAATATA...
7959,G000006925,G000299455,91.489,47,4,0,4416629,4416675,3399520,3399566,9.011090e-08,67,CTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT,CTGATGACAAACGCAACATTGCCTGATGCGCTACGCTTATCAGGCCT
8142,G000006925,G000299455,78.862,123,15,11,4416630,4416741,367155,367033,9.011090e-08,67,TGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT...,TGATGACCAACGAGAAATTGCCTGATGCGCTACGCTTATCAGGCCT...
8999,G000006925,G000299455,76.296,135,22,10,4416631,4416755,4515538,4515404,3.416360e-07,66,GATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTA...,GATGACAAACGCAAAGCAGCCTTATGCGCTACGCTTATCAGGTCTA...
9551,G000006925,G000299455,78.505,107,13,10,4416641,4416737,5006836,5006942,1.295240e-06,64,GCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCT...,GCAAAATTGCCTGATGCGCTACGTTTATCAAGCCTACGAAATCTCT...
12418,G000006925,G000299455,79.268,82,17,0,4416622,4416703,4656086,4656005,1.861760e-05,60,ATTAAGTCTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTA...,ATTCAGACTGCTGATAAATGCAATACTGCCTGATGCGCTATGCCGA...
12562,G000006925,G000299455,88.889,45,5,0,4416633,4416677,372866,372910,7.058480e-05,58,TGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTAC,TGACAAATGTAAAATTGCCTGATGCGCTGCGCTTATCAGGCCTAC
12640,G000006925,G000299455,88.889,45,5,0,4416631,4416675,952963,953007,7.058480e-05,58,GATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT,GATGACAAATGCAAAACTGCCTGATGCGCTACGCTTATCATGCCT
14941,G000006925,G000299455,87.234,47,6,0,4416629,4416675,679680,679634,2.676070e-04,56,CTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT,CTGATGGCAACCGCAAAAATGCCTGATGCGCTACGCTTATCAGGCCT
15451,G000006925,G000299455,90.244,41,4,0,4416635,4416675,4235284,4235244,2.676070e-04,56,ACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT,ACAAACGCAAAATTGCCTGATGCGCTGCGCTTATCAGGCCT
17782,G000006925,G000299455,77.228,101,22,1,4416645,4416745,3973265,3973364,3.846550e-03,52,AATCGCCCGATGCGCTACGCTTATCAGGCCTACGTGATTCCTGCAA...,AATTGCCTGCTGCGCTACGCTTATCAGGCCTACAAAGTTTCTG-AA...
18103,G000006925,G000299455,93.939,33,2,0,4416645,4416677,159099,159067,3.846550e-03,52,AATCGCCCGATGCGCTACGCTTATCAGGCCTAC,AATTGCCTGATGCGCTACGCTTATCAGGCCTAC
19595,G000006925,G000299455,78.378,74,16,0,4416630,4416703,2326927,2327000,1.458340e-02,50,TGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT...,TGATGACAAAGGTTACACCGTCTGACGTGCTACGCCTGTCAGGCCT...
19840,G000006925,G000299455,96.552,29,1,0,4416649,4416677,4079759,4079787,1.458340e-02,50,GCCCGATGCGCTACGCTTATCAGGCCTAC,GCCTGATGCGCTACGCTTATCAGGCCTAC
20048,G000006925,G000299455,96.552,29,1,0,4416649,4416677,4723733,4723761,1.458340e-02,50,GCCCGATGCGCTACGCTTATCAGGCCTAC,GCCTGATGCGCTACGCTTATCAGGCCTAC
20521,G000006925,G000299455,96.552,29,1,0,4416649,4416677,1404126,1404098,1.458340e-02,50,GCCCGATGCGCTACGCTTATCAGGCCTAC,GCCTGATGCGCTACGCTTATCAGGCCTAC
20831,G000006925,G000299455,96.552,29,1,0,4416649,4416677,3057513,3057485,1.458340e-02,50,GCCCGATGCGCTACGCTTATCAGGCCTAC,GCCTGATGCGCTACGCTTATCAGGCCTAC
25229,G000006925,G000299455,84.444,45,7,0,4416633,4416677,4725148,4725104,2.096190e-01,46,TGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTAC,TGACAAACGTATCATTGCCTGATGCGCTTCGCTTATCAGGCCTAC
25639,G000006925,G000299455,82.979,47,8,0,4416629,4416675,1228280,1228326,7.947270e-01,44,CTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCT,CTGATGCCAAACCCCAGATTGCCCGATGCGCTGCGCTTATCGGGCCT
26101,G000006925,G000299455,93.103,29,2,0,4416649,4416677,3527627,3527655,7.947270e-01,44,GCCCGATGCGCTACGCTTATCAGGCCTAC,GCCTGATGCGCTACGCTTATCTGGCCTAC
26213,G000006925,G000299455,88.571,35,4,0,4416643,4416677,4054119,4054153,7.947270e-01,44,AAAATCGCCCGATGCGCTACGCTTATCAGGCCTAC,AAAATTGCCTGATACGCTGCGCTTATCAGGCCTAC
28248,G000006925,G000299455,90.323,31,3,0,4416649,4416679,641257,641287,3.013040e+00,42,GCCCGATGCGCTACGCTTATCAGGCCTACGT,GCCTGATGCGCTTCGCTTATCAGGTCTACGT
29088,G000006925,G000299455,81.633,49,9,0,4416629,4416677,5069773,5069821,3.013040e+00,42,CTGATGACAAAAGCAAAATCGCCCGATGCGCTACGCTTATCAGGCCTAC,CTGATGACAAGCGTATGATTGCCTGATGCGCTGCGCTTATCAGCCCTAC
29638,G000006925,G000299455,100.000,22,0,0,4416656,4416677,2306643,2306622,3.013040e+00,42,GCGCTACGCTTATCAGGCCTAC,GCGCTACGCTTATCAGGCCTAC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
90,G000006925,G000299455,99.089,13057,112,7,2602941,2615991,1444017,1430962,0.0,24390,TCGGGCTATTTATTTACGTCAGGAATCCTGAAAAATCAGCCCGGCG...,TCGGGCTATTTATTTACGTCAGGAATCCTGAAAAATCAGCCCGGCG...
904,G000006925,G000299455,98.060,773,14,1,2602175,2602947,1444726,1443955,0.0,1390,ATGGCGATGTCCGCTGGCGTGTTTATGGCGATCGGATTTACTTTTT...,ATGGCGATGTCCGCTGGCGTGTTTATGGCGATCGGATTTACTTTTT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
91,G000006925,G000299455,98.703,13187,170,1,2313327,2326513,1765832,1752647,0.000000e+00,24359,TAGCCCGATGGCATCACCATCGGGCCTCTTTTTATTTACTCTCCTG...,TAGCCCGATGGCATCACCATCGGGCCTCTTTTTATTTACTCTCCTG...
3248,G000006925,G000299455,87.500,152,17,2,2313177,2313327,3816019,3815869,1.036190e-36,164,GAGATTTATGACAAACGCAAAACTGCCTGATGCGCTACGCTTATCA...,GAGACTGATGACAAACGCTAAACTGCCTGATGCGCTACGCTTATCA...
3468,G000006925,G000299455,85.714,140,19,1,2313188,2313327,988656,988794,6.357800e-31,144,CAAACGCAAAACTGCCTGATGCGCTACGCTTATCAGGCCTACGTGG...,CAAAAGCAAAATTGCCTGATGCGCTACGCTTATCAGGCCTACACGT...
3784,G000006925,G000299455,81.944,144,26,0,2313184,2313327,5069776,5069919,1.028930e-25,127,ATGACAAACGCAAAACTGCCTGATGCGCTACGCTTATCAGGCCTAC...,ATGACAAGCGTATGATTGCCTGATGCGCTGCGCTTATCAGCCCTAC...
3803,G000006925,G000299455,81.944,144,26,0,2313185,2313328,4656075,4655932,1.028930e-25,127,TGACAAACGCAAAACTGCCTGATGCGCTACGCTTATCAGGCCTACG...,TGATAAATGCAATACTGCCTGATGCGCTATGCCGATCAGGCCTACG...
3858,G000006925,G000299455,85.075,134,18,2,2313200,2313332,4689306,4689438,1.478980e-24,123,TGCCTGATGCGCTACGCTTATCAGGCCTACGTGGATCGAT-CAATT...,TGCCTGATGCACTACGTTTATCCGGCCTACATG-ATCTCTGCAATA...
5073,G000006925,G000299455,86.207,87,11,1,2313241,2313327,1147473,1147558,3.873670e-14,89,AATTTATTGAATTTACACAATTTTGTAGGCCGGATAAGGCGTTCAC...,AATTCATTGAATTTAATTGGTTTTGTAGGCCGGATAAGGCGTTAAC...
5395,G000006925,G000299455,79.114,158,30,3,2313176,2313331,3660729,3660885,5.567960e-13,85,TGAGATTTATGACAAACGCAAAACTGCCTGATGCGCTACGCTTATC...,TGAGAGTGAAGATAAACGCAAAATTACCTGATGCGCTACGCTTGCC...
12642,G000006925,G000299455,82.540,63,11,0,2313265,2313327,953026,953088,7.058480e-05,58,GTAGGCCGGATAAGGCGTTCACGCCGCATCCGGCATAAACTAAGCG...,GTAGGCGGGATAAGGTGTTTACGCCGCATCCGGCATGGAAAACGCG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
83,G000006925,G000299455,98.743,13370,164,4,3040656,3054024,956197,942831,0.0,24709,TTACTTAATCACCCCATTGCGCCGCAGTTGTTCGGTATCTTTTTTC...,TTACTTAATCACCCCATTGCGCCGCAGTTGTTCGGTATCTTTTTTC...
92,G000006925,G000299455,99.897,12670,12,1,3052415,3065083,4735655,4748324,0.0,24276,GAAATTTGATTGACGAGACGAGGCGAATCAGGTTTAATGCGCCCCG...,GAAATTAGGTTGACGAGATGTGCAGATTACGGTTTAATGCGCCCCG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
93,G000006925,G000299455,98.078,13269,241,14,4103083,4116338,5060698,5047431,0.0,24022,GGATATTGCGGCCACTCATCGGTCAGTTGATTACGCAGGGCGTAAA...,GGATATTGCGGCCACTCATCGGTCAGTTGATTACGCAGGGCGTAAA...
737,G000006925,G000299455,99.098,776,7,0,4102314,4103089,4588745,4589520,0.0,1452,TGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...,TGGTAATGACTCCAACTTACTGATAGTGTTTTATGTTCAGATAATG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
98,G000006925,G000299455,99.138,12411,87,20,1815406,1827803,2737538,2749941,0.0,23197,GAACGGTTTAAACCTGATTTTGCCCGGACATTGCGCCCCGGCTGGC...,GAACGGTTTAAACCTGATTTTGCCCGGACATTGCGCCCCGGCTGGC...
510,G000006925,G000299455,98.492,1393,21,0,1815406,1816798,2270570,2269178,0.0,2557,GAACGGTTTAAACCTGATTTTGCCCGGACATTGCGCCCCGGCTGGC...,GAACGGTTTAAACCTGATTTTGCCCGGACATTGCGCCCCGGCTGGC...

In [25]:
for l in check_list:
    qStart, qEnd, sStart, sEnd = l[0], l[1], l[2], l[3]
    sub_df = df[(df.sStart <= sStart) & (df.sEnd >= sEnd)]
    if sub_df.shape[0] > 1:
        display(sub_df)

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
0,G00009306,G90004803,84.447,2919,411,43,334121,337010,663556,660652,0.0,2715,TCTCTCGGATCATTAGTACTGGTTAGCTCAACGCATCTCTACGCTT...,TCTCACGGGTCATTAGTATCGGTTAGCTCAACGCTTCACAACGCTT...
1,G00009306,G90004803,84.447,2919,411,43,35427,38316,663556,660652,0.0,2715,TCTCTCGGATCATTAGTACTGGTTAGCTCAACGCATCTCTACGCTT...,TCTCACGGGTCATTAGTATCGGTTAGCTCAACGCTTCACAACGCTT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
0,G00009306,G90004803,84.447,2919,411,43,334121,337010,663556,660652,0.0,2715,TCTCTCGGATCATTAGTACTGGTTAGCTCAACGCATCTCTACGCTT...,TCTCACGGGTCATTAGTATCGGTTAGCTCAACGCTTCACAACGCTT...
1,G00009306,G90004803,84.447,2919,411,43,35427,38316,663556,660652,0.0,2715,TCTCTCGGATCATTAGTACTGGTTAGCTCAACGCATCTCTACGCTT...,TCTCACGGGTCATTAGTATCGGTTAGCTCAACGCTTCACAACGCTT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
2,G00009306,G90004803,87.744,1330,156,7,337282,338609,659934,658610,0.0,1559,TTGTTTTTTTAAGGAGGTGATCCAACCACAGGTTCCCCTACGGTTA...,TTGTTTTAGTAAGGAGGTGATCCAACCGCAGGTTCCCCTACGGTTA...
3,G00009306,G90004803,87.744,1330,156,7,38665,39992,659934,658610,0.0,1559,TTGTTTTTTTAAGGAGGTGATCCAACCACAGGTTCCCCTACGGTTA...,TTGTTTTAGTAAGGAGGTGATCCAACCGCAGGTTCCCCTACGGTTA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
2,G00009306,G90004803,87.744,1330,156,7,337282,338609,659934,658610,0.0,1559,TTGTTTTTTTAAGGAGGTGATCCAACCACAGGTTCCCCTACGGTTA...,TTGTTTTAGTAAGGAGGTGATCCAACCGCAGGTTCCCCTACGGTTA...
3,G00009306,G90004803,87.744,1330,156,7,38665,39992,659934,658610,0.0,1559,TTGTTTTTTTAAGGAGGTGATCCAACCACAGGTTCCCCTACGGTTA...,TTGTTTTAGTAAGGAGGTGATCCAACCGCAGGTTCCCCTACGGTTA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
11,G00009306,G90004803,73.123,1012,272,0,13726,14737,507506,506495,1.224880e-102,377,ATGTTTAAAAAAATTAGAGGAATCTTTTCGAATGATTTATCCATCG...,ATGTTCAAAAAATTTCGTGGCATATTTTCTAATGACTTATCTATCG...
12,G00009306,G90004803,73.035,1005,271,0,2906,3910,506495,507499,2.530690e-100,369,TATCTATCATCTCCAAAGCTTTCCCACCGCCCCTTGCGACACAAGT...,TATCGATCATTTCTAATGCCTTTCCTCCACCACGAGCAACACAAGT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
10,G00009306,G90004803,75.978,716,172,0,555246,555961,713201,713916,5.928510e-105,385,TCATCTAAAAAACTTCTTAGTAGTTCTGAACGGCTAGGATGTCTTA...,TCATCTAAAAAACTACGAAGGACTTCAGAACGGCTAGGATGACGTA...
13,G00009306,G90004803,76.555,627,147,0,573738,574364,713916,713290,7.515540e-97,358,GCTAAAAAAGAAATGGTAGAGGCAAATTTAAGATTGGTAATTTCAA...,GCTAAAAAAGAAATGGTTGAAGCAAATCTACGTTTAGTTATCTCTA...
372,G00009306,G90004803,80.769,52,10,0,7437,7488,713782,713833,6.265970e-02,42,AAATTTCTGAACTGCTTTCATCAAACCGACGTTTCCTTCTTGAATT...,AAATTTATCTACTGCCTTCATCAAACCGATATTACCCTCCTGAATA...
373,G00009306,G90004803,80.769,52,10,0,10154,10205,713833,713782,6.265970e-02,42,AGATCTAATTCAAGAAGGAAACGTCGGTTTGATGAAAGCAGTTCAG...,AGATCTTATTCAGGAGGGTAATATCGGTTTGATGAAGGCAGTAGAT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
14,G00009306,G90004803,72.46,1053,290,0,409947,410999,60499,59447,4.095630e-95,352,AACCATTTCTATATCGGATGGAAGCTCGACAACTCCAGTCACATCT...,AACCATTTCAATATCTTTTGGTAATTCGATAGTACCAGTTACATCA...
458,G00009306,G90004803,100.00,20,0,0,500371,500390,59568,59549,9.006620e-01,39,CCATAAATTTTGGCTAGAAC,CCATAAATTTTGGCTAGAAC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
15,G00009306,G90004803,72.46,1053,290,0,409947,410999,588735,587683,4.095630e-95,352,AACCATTTCTATATCGGATGGAAGCTCGACAACTCCAGTCACATCT...,AACCATTTCAATATCTTTTGGTAATTCGATAGTACCAGTTACATCA...
543,G00009306,G90004803,100.00,20,0,0,500371,500390,587804,587785,9.006620e-01,39,CCATAAATTTTGGCTAGAAC,CCATAAATTTTGGCTAGAAC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
16,G00009306,G90004803,73.216,911,244,0,402250,403160,68627,67717,8.461890e-93,344,ATATTGATCCCTAGAGATCTGATCTCTTTCAACAAAACATTGAAAG...,ATATTGATACCCAGTGAACGAATCTCTTTTAATAAAACATTAAAAG...
617,G00009306,G90004803,100.000,19,0,0,374651,374669,67851,67869,3.414670e+00,37,AATTAATCCAATTGAAGAT,AATTAATCCAATTGAAGAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
25,G00009306,G90004803,71.011,821,238,0,161472,162292,163765,162945,3.982120e-51,206,TTAGCGGTCGCAATAAACATCACTTCAGATAAATCATAATCTATCT...,TTAGAGGTAGCAACAAACATTACATCAGAGAGGTCATAGTCCACTT...
649,G00009306,G90004803,89.286,28,3,0,83496,83523,163275,163302,3.414670e+00,37,AAAAAAGATTTTGTGAAATCGCAAGAAA,AAAAAAGATTTGGCGAAAGCGCAAGAAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
34,G00009306,G90004803,71.518,639,182,0,199653,200291,744402,743764,5.048110e-43,179,TTAGAGAGCTTAAAAGAAGGAATAGAAGTTCCGGGAATTGTAAAAA...,TTAGAAAACTTACAGGAAGGTACAAAAGTTAAAGGTACTGTAAAGA...
565,G00009306,G90004803,100.000,20,0,0,277062,277081,744002,744021,9.006620e-01,39,GAAGGATGAATATTTTTATT,GAAGGATGAATATTTTTATT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
39,G00009306,G90004803,85.065,154,18,5,411060,411210,587559,587408,1.322180e-32,144,TGCTGATAGGCAGATTTGAACTGCCGACCTCACCTATACCAAAGGT...,TGCTGATAGGCAGAATTGAACTGCCGACCTCACCCTTACCAAGGGT...
186,G00009306,G90004803,90.385,52,4,1,38571,38622,587544,587494,1.021220e-07,62,TTGAACCACCGACCTCACCCTTATCAAGGGTGTGCTCTAACCATCT...,TTGAACTGCCGACCTCACCCTTACCAAGGGTGTGCTCTA-CCAACT...
541,G00009306,G90004803,100.000,20,0,0,242068,242087,587492,587511,9.006620e-01,39,TATAGCTCAGTTGGTAGAGC,TATAGCTCAGTTGGTAGAGC
542,G00009306,G90004803,100.000,20,0,0,470120,470139,587494,587513,9.006620e-01,39,TAGCTCAGTTGGTAGAGCAC,TAGCTCAGTTGGTAGAGCAC
763,G00009306,G90004803,100.000,19,0,0,237431,237449,587494,587512,3.414670e+00,37,TAGCTCAGTTGGTAGAGCA,TAGCTCAGTTGGTAGAGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
41,G00009306,G90004803,73.761,343,90,0,565113,565455,787647,787305,1.900480e-31,141,TACCCAACATTCTCATCGTACCGCCGATATTCACAATAACTTCGGT...,TACCGAGCATTTTCATAATGCCGCCCATATTGACTATAATTTCAGT...
42,G00009306,G90004803,73.761,343,90,0,564244,564586,787305,787647,1.900480e-31,141,ATGGCTAGTAGAGGTATAAATAAGGTAATATTAATTGGTTATTTAG...,ATGGCTAGCAGAGGTGTTAATAAAGTAATTCTAGTTGGAAATCTCG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
62,G00009306,G90004803,76.279,215,51,0,7300,7514,555619,555833,4.420980e-25,119,AGATTGAAGAAAAGTTTTCTTTGTGCTTTTGTTGTTGCAACTTTCA...,AGATTAAAGAATAGCTTACGTTGTGCTTTTGTAGTCGCCACTTTTA...
63,G00009306,G90004803,76.279,215,51,0,10128,10342,555833,555619,4.420980e-25,119,TATTCAGGATACGGATTGTTACAAGCAGATCTAATTCAAGAAGGAA...,TATTCAGGTTACGGTTTGCCGCAAGCTGATTTGATTCAAGAAGGAA...
534,G00009306,G90004803,87.500,32,4,0,573828,573859,555800,555769,9.006620e-01,39,ATTCAAGAAGGAAACATAGGATTAATGAAAGC,ATTCAAGAAGGAAACATCGGCATGATGAAAGC
535,G00009306,G90004803,87.500,32,4,0,555840,555871,555769,555800,9.006620e-01,39,GCTTTCATTAATCCTATGTTTCCTTCTTGAAT,GCTTTCATCATGCCGATGTTTCCTTCTTGAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
70,G00009306,G90004803,94.366,71,4,0,292008,292078,180965,180895,2.409230e-23,114,CGCCCTACAGGACTCGAACCTGTGATCTACGACTTAGAAGGTCGTT...,CGCCCTACAGGATTCGAACCTGTGATCTACGGCTTAGAAGGCCGTT...
474,G00009306,G90004803,80.328,61,11,1,237430,237489,180900,180960,9.006620e-01,39,TTAGCTCAGTTGG-TAGAGCAGTTGACTTTTAATCAATTGGTCACA...,TTAGCTCAGTTGGATAGAGCAACGGCCTTCTAAGCCGTAGATCACA...
655,G00009306,G90004803,79.365,63,12,1,66807,66868,180899,180961,3.414670e+00,37,CTTAGCTCAGAAGG-TAGAGCAACTGACTTGTAATCAGTAGGTCAC...,CTTAGCTCAGTTGGATAGAGCAACGGCCTTCTAAGCCGTAGATCAC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
77,G00009306,G90004803,78.378,185,26,14,338683,338853,658565,658381,4.977660e-21,106,TTACGCGGTATTAGCTACCGTTTCCGATAGTTATCCCCCATCTTTA...,TTATGCGGTATTAGCTACCGTTTCCAGTAGTTATCCCCCTCCATTG...
78,G00009306,G90004803,78.378,185,26,14,40066,40236,658565,658381,4.977660e-21,106,TTACGCGGTATTAGCTACCGTTTCCGATAGTTATCCCCCATCTTTA...,TTATGCGGTATTAGCTACCGTTTCCAGTAGTTATCCCCCTCCATTG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
77,G00009306,G90004803,78.378,185,26,14,338683,338853,658565,658381,4.977660e-21,106,TTACGCGGTATTAGCTACCGTTTCCGATAGTTATCCCCCATCTTTA...,TTATGCGGTATTAGCTACCGTTTCCAGTAGTTATCCCCCTCCATTG...
78,G00009306,G90004803,78.378,185,26,14,40066,40236,658565,658381,4.977660e-21,106,TTACGCGGTATTAGCTACCGTTTCCGATAGTTATCCCCCATCTTTA...,TTATGCGGTATTAGCTACCGTTTCCAGTAGTTATCCCCCTCCATTG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
82,G00009306,G90004803,90.541,74,7,0,237423,237496,497865,497792,7.154820e-20,102,TGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTG...,TGGGTCGTTAGCTCAGCTGGTAGAGCAGTTGACTCTTAATCAATTG...
363,G00009306,G90004803,83.721,43,7,0,555171,555213,497803,497845,6.265970e-02,42,GGATTCGAACCAGCGACCAAACGATTATGAGTCGTCTGCTCTA,GGATTCGAACCTACGACCAATTGATTAAGAGTCAACTGCTCTA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
93,G00009306,G90004803,77.622,143,32,0,5635,5777,511007,511149,2.124810e-16,91,AAAGTTATTTCAATATTCCTTCAATTATTTCTGCCGCAGAAGTAAC...,AAAGTTATCTCAATATTCCTGCTATTATTTCTGCAGCAGAAATTAC...
94,G00009306,G90004803,77.622,143,32,0,11865,12007,511149,511007,2.124810e-16,91,AGGACCTATGAATACAAAACCCGATTTTTCAACTTTTTCTGCAAAG...,AGGACCGATGAATATAAAGCCAGAACGTTCCACTTGTTCAGCGAAA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
97,G00009306,G90004803,71.753,308,87,0,572655,572962,714954,714647,2.124810e-16,91,GATAATCTTCCGGAAGATATAGTTGATTCAGATCAAATAGAAGATA...,GATCATCTACCGGAAGATATTATCGACTCTGATCAAATTGAAGATA...
98,G00009306,G90004803,71.753,308,87,0,556737,557044,714647,714954,2.124810e-16,91,TGATTAATACCATCTTCTATTCTTTTAGCAATGTCAATTTCGCCTT...,TGATTAATACCATCTTCAATACGTTTAGCGATATCAATTTCACCTT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
106,G00009306,G90004803,76.667,150,35,0,570829,570978,716818,716669,3.054170e-15,87,TGTCCATTTCATAAAGAGAAGACCCCTTCTTTCACTGTGAATAAAG...,TGTCCATTTCATCAAGAGAAAACTCCATCATTTACCGTAAACGGAG...
107,G00009306,G90004803,76.667,150,35,0,558721,558870,716669,716818,3.054170e-15,87,AAGTTCTTTGATAGCTTCAACGAAACCGACTCCTTTATAATTCATC...,AAGTTCTTCGATAGATTCGACGAATTCCAGTCGGTCGTAATGCATC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
134,G00009306,G90004803,76.692,133,31,0,6455,6587,511827,511959,2.392360e-12,77,TGGGCATTCTATAGAATGTAGAATAAATGCAGAAGATAGTATTAAT...,TGGTCATGCGATAGAATGTCGTATTAATGCTGAAGATCCTATTAAC...
135,G00009306,G90004803,76.692,133,31,0,11055,11187,511959,511827,2.392360e-12,77,ATATCCAGTATAAATATGAGATTCCCATCGGATTCCCAATCCCCCA...,ATAACCAGTATAAATATGAGATTCCCAACGTACACCAAAACCACCT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
164,G00009306,G90004803,74.497,149,38,0,6045,6193,511417,511565,1.873960e-09,67,AATGATGAAGTATATATGGAAAAATTTTTAAATAATCCACGTCATA...,AATGATGTAGTCTACATGGAAAAGTATTTGGAAAATCCACGCCATA...
165,G00009306,G90004803,74.497,149,38,0,11449,11597,511565,511417,1.873960e-09,67,GGTGCTTCTTCAATTATCTTTTGATTGCGACGTTGTATTGAACAAT...,GGTGCTTCTTCTACTACTTTTTGATGACGACGTTGAATAGAACAGT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
178,G00009306,G90004803,81.944,72,13,0,35204,35275,513698,513769,2.693610e-08,64,TCCCTACTCTCGCATAAATAAAGTATACACTACCATCGGCACCACG...,TCCCTACTCTCGCATGGGGAAACCCCAAACTACCATCGGCGCTACG...
179,G00009306,G90004803,81.944,72,13,0,333898,333969,513698,513769,2.693610e-08,64,TCCCTACTCTCGCATAAATAAAGTATACACTACCATCGGCACCACG...,TCCCTACTCTCGCATGGGGAAACCCCAAACTACCATCGGCGCTACG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
178,G00009306,G90004803,81.944,72,13,0,35204,35275,513698,513769,2.693610e-08,64,TCCCTACTCTCGCATAAATAAAGTATACACTACCATCGGCACCACG...,TCCCTACTCTCGCATGGGGAAACCCCAAACTACCATCGGCGCTACG...
179,G00009306,G90004803,81.944,72,13,0,333898,333969,513698,513769,2.693610e-08,64,TCCCTACTCTCGCATAAATAAAGTATACACTACCATCGGCACCACG...,TCCCTACTCTCGCATGGGGAAACCCCAAACTACCATCGGCGCTACG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
186,G00009306,G90004803,90.385,52,4,1,38571,38622,587544,587494,1.021220e-07,62,TTGAACCACCGACCTCACCCTTATCAAGGGTGTGCTCTAACCATCT...,TTGAACTGCCGACCTCACCCTTACCAAGGGTGTGCTCTA-CCAACT...
541,G00009306,G90004803,100.000,20,0,0,242068,242087,587492,587511,9.006620e-01,39,TATAGCTCAGTTGGTAGAGC,TATAGCTCAGTTGGTAGAGC
542,G00009306,G90004803,100.000,20,0,0,470120,470139,587494,587513,9.006620e-01,39,TAGCTCAGTTGGTAGAGCAC,TAGCTCAGTTGGTAGAGCAC
763,G00009306,G90004803,100.000,19,0,0,237431,237449,587494,587512,3.414670e+00,37,TAGCTCAGTTGGTAGAGCA,TAGCTCAGTTGGTAGAGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
226,G00009306,G90004803,81.967,61,11,0,4712,4772,510115,510175,0.000021,54,TTGATTTTATTTTGATTAATCCTGGAGCTTTTGCACATACAAGTGT...,TTGATTTTATTATTATTAATCCTGCAGCATTTACTCATACTAGTAT...
227,G00009306,G90004803,81.967,61,11,0,12870,12930,510175,510115,0.000021,54,GCATCTCTTAAAGCAACACTTGTATGTGCAAAAGCTCCAGGATTAA...,GCATCACGTAAAGCGATACTAGTATGAGTAAATGCTGCAGGATTAA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
61,G00009306,G90004803,79.781,183,30,7,46792,46970,381228,381407,4.420980e-25,119,ACGCATCCAGAAGGATTTGAACCTCCGACCTCTCGGTTCGTAGCCG...,ACGCATCCGAGAGGATTCGAACCTCCGACCGCTCGGTTCGTAGCCG...
258,G00009306,G90004803,100.000,26,0,0,440252,440277,381339,381314,3.032780e-04,50,CGAGGGTTCGAATCCCTCTCTCACCG,CGAGGGTTCGAATCCCTCTCTCACCG

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
274,G00009306,G90004803,75.0,100,25,0,6271,6370,511643,511742,0.00115,48,GTGGAGTCGGTACTTTCGAATTTCTTTATAAGAACGAATCGATGTA...,GTGGCGCCGGTACTTTTGAATTTCTCTATGAAAACGGTGAATTTTT...
275,G00009306,G90004803,75.0,100,25,0,11272,11371,511742,511643,0.00115,48,ATCATCTCAGTGATAGTATGTTCAACTTGAATTCTCGTATTCACTT...,ATCATCTCAGTAATTGGATGCTCTACTTGAATTCGAGTGTTCATTT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
184,G00009306,G90004803,79.070,86,18,0,469843,469928,367490,367575,1.021220e-07,62,AATAACCAAGAATATAAAGCTGTTCGAATATTTCCTAAATGTAGAT...,AATAACCACGAATATAGCGCAGTACGAATACCACCGATATGTAAAT...
292,G00009306,G90004803,80.702,57,11,0,224720,224776,367578,367522,4.359280e-03,46,TTTAAGAAAATTCATACTCGTTTTCCTCCTTATCCAAATGGATATC...,TTTATGAAAATTAAAACCCGTTTTTCACCTAGTCCAACTGGATATT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
45,G00009306,G90004803,96.25,80,3,0,237422,237501,367908,367987,2.731730e-30,137,GTGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATT...,GTGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATT...
293,G00009306,G90004803,80.00,60,12,0,66808,66867,367916,367975,4.359280e-03,46,TTAGCTCAGAAGGTAGAGCAACTGACTTGTAATCAGTAGGTCACCA...,TTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTGGTCGCAG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
330,G00009306,G90004803,81.132,53,10,0,2098,2150,505715,505767,0.016527,44,GGATAGCCTTTTGGAAATTTTCCTCCTAATCCAGAGGTTACCAGAA...,GGATATCCTTCTGGAAATCGACCGCCTAAACCAGAAGTTACCAGTA...
331,G00009306,G90004803,81.132,53,10,0,15493,15545,505767,505715,0.016527,44,GGAGATATTCTGGTAACCTCTGGATTAGGAGGAAAATTTCCAAAAG...,GGAGATGTACTGGTAACTTCTGGTTTAGGCGGTCGATTTCCAGAAG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
340,G00009306,G90004803,73.832,107,28,0,570448,570554,717259,717153,0.016527,44,GAAAATGAGCCGTTTGACTTAGCTTTTCGAAGATTCAAACGTTCTT...,GAAAACGAGCCATTTGACATAGCAGTACGTCGTTTTAAGCGTTCCT...
341,G00009306,G90004803,73.832,107,28,0,559145,559251,717153,717259,0.016527,44,GTTGTCGGTTTTTCATAAAATTCTCTTCTCCTGACTTCTGCAAGAA...,GTTGTTGGTTTTTCATAGAACTCGCGACGACGAACTTCAGCTAGAA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
223,G00009306,G90004803,78.889,90,18,1,440191,440279,314414,314503,0.000021,54,TGGTGAGATGTCCGAGTGGATTAAGGAACGTACTTGGAAAGTACGA...,TGGTGAGGTGTCCGAGTGGCTGAAGGAGCACGCTTGGAAAGTGTGT...
356,G00009306,G90004803,92.857,28,2,0,46881,46908,314501,314474,0.062660,42,CGGTGAGAGAGGGATTCGAACCCTCGAT,CGGTGAGGAAGGGATTCGAACCCTCGAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
367,G00009306,G90004803,96.000,25,1,0,139141,139165,604200,604176,0.06266,42,TTTTTTAAAATTTATTTTTAATAAA,TTTTTTAAAATTTATTTTTTATAAA
764,G00009306,G90004803,95.455,22,1,0,106857,106878,604182,604203,3.41467,37,AAAAATAAATTTTTAAAAAAGT,AAAAATAAATTTTAAAAAAAGT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
371,G00009306,G90004803,100.0,22,0,0,97566,97587,703900,703879,0.06266,42,TAAATAATTTTTTAAATTTTTT,TAAATAATTTTTTAAATTTTTT
792,G00009306,G90004803,100.0,19,0,0,209053,209071,703883,703901,3.41467,37,AATTTAAAAAATTATTTAT,AATTTAAAAAATTATTTAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
10,G00009306,G90004803,75.978,716,172,0,555246,555961,713201,713916,5.928510e-105,385,TCATCTAAAAAACTTCTTAGTAGTTCTGAACGGCTAGGATGTCTTA...,TCATCTAAAAAACTACGAAGGACTTCAGAACGGCTAGGATGACGTA...
372,G00009306,G90004803,80.769,52,10,0,7437,7488,713782,713833,6.265970e-02,42,AAATTTCTGAACTGCTTTCATCAAACCGACGTTTCCTTCTTGAATT...,AAATTTATCTACTGCCTTCATCAAACCGATATTACCCTCCTGAATA...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
10,G00009306,G90004803,75.978,716,172,0,555246,555961,713201,713916,5.928510e-105,385,TCATCTAAAAAACTTCTTAGTAGTTCTGAACGGCTAGGATGTCTTA...,TCATCTAAAAAACTACGAAGGACTTCAGAACGGCTAGGATGACGTA...
372,G00009306,G90004803,80.769,52,10,0,7437,7488,713782,713833,6.265970e-02,42,AAATTTCTGAACTGCTTTCATCAAACCGACGTTTCCTTCTTGAATT...,AAATTTATCTACTGCCTTCATCAAACCGATATTACCCTCCTGAATA...
373,G00009306,G90004803,80.769,52,10,0,10154,10205,713833,713782,6.265970e-02,42,AGATCTAATTCAAGAAGGAAACGTCGGTTTGATGAAAGCAGTTCAG...,AGATCTTATTCAGGAGGGTAATATCGGTTTGATGAAGGCAGTAGAT...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
113,G00009306,G90004803,88.158,76,8,1,224410,224484,908006,908081,1.157920e-14,85,AATGGCTACGACAGGGATTGAACCTGTGACTTCAGCGTTATGAGCG...,AATAGCTACGACAGGAATCGAACCTGTGACCTCAGCATTATGAGTG...
381,G00009306,G90004803,83.721,43,7,0,38581,38623,908033,908075,6.265970e-02,42,GACCTCACCCTTATCAAGGGTGTGCTCTAACCATCTGAGCTAC,GACCTCAGCATTATGAGTGCTGTGCTCTAACCAGCTGAGCTAC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
384,G00009306,G90004803,83.721,43,7,0,570347,570389,914138,914096,0.06266,42,AATAAATATTTTGTAATTTTAAACAGATAATCTTTTATAATAT,AATAATGATTATTTAATTTTAAACATTTAATATTTTATAATAT
385,G00009306,G90004803,83.721,43,7,0,559310,559352,914096,914138,0.06266,42,ATATTATAAAAGATTATCTGTTTAAAATTACAAAATATTTATT,ATATTATAAAATATTAAATGTTTAAAATTAAATAATCATTATT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
407,G00009306,G90004803,100.000,21,0,0,564768,564788,291327,291347,0.237561,41,TTTTTAAAAAAATATTTAATT,TTTTTAAAAAAATATTTAATT
489,G00009306,G90004803,92.308,26,2,0,72555,72580,291327,291352,0.900662,39,TTTCTAAAAAAATATTTAATTCTATT,TTTTTAAAAAAATATTTAATTTTATT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
433,G00009306,G90004803,83.333,42,7,0,569296,569337,718667,718626,0.237561,41,CCAGCATACGCTATCATTGCTCCATTATCAGTACAAAATTCA,CCAGCGTATGCAATCATAGCACCATTATCCGTACAAAAGTCA
434,G00009306,G90004803,83.333,42,7,0,560362,560403,718626,718667,0.237561,41,TGAATTTTGTACTGATAATGGAGCAATGATAGCGTATGCTGG,TGACTTTTGTACGGATAATGGTGCTATGATTGCATACGCTGG

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
113,G00009306,G90004803,88.158,76,8,1,224410,224484,908006,908081,1.157920e-14,85,AATGGCTACGACAGGGATTGAACCTGTGACTTCAGCGTTATGAGCG...,AATAGCTACGACAGGAATCGAACCTGTGACCTCAGCATTATGAGTG...
381,G00009306,G90004803,83.721,43,7,0,38581,38623,908033,908075,6.265970e-02,42,GACCTCACCCTTATCAAGGGTGTGCTCTAACCATCTGAGCTAC,GACCTCAGCATTATGAGTGCTGTGCTCTAACCAGCTGAGCTAC
447,G00009306,G90004803,100.000,21,0,0,237468,237488,908036,908016,2.375610e-01,41,GGTCACAGGTTCGATTCCTGT,GGTCACAGGTTCGATTCCTGT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
452,G00009306,G90004803,100.0,20,0,0,369111,369130,31638,31657,0.900662,39,AAATTTTTAATTAATTAATA,AAATTTTTAATTAATTAATA
453,G00009306,G90004803,100.0,20,0,0,124338,124357,31658,31639,0.900662,39,CTATTAATTAATTAAAAATT,CTATTAATTAATTAAAAATT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
456,G00009306,G90004803,87.500,32,4,0,127385,127416,40211,40180,0.900662,39,AAATTACTTAATGATCTTTTTTTTATTTATTA,AAATTAATCAATGATCTTTATTTTATTTTTTA
606,G00009306,G90004803,89.286,28,3,0,276928,276955,40206,40233,3.414670,37,TAATTTTTTAGCTTATATTTATTAATAA,TAATTTTTTATATTATATTTATTACTAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
474,G00009306,G90004803,80.328,61,11,1,237430,237489,180900,180960,0.900662,39,TTAGCTCAGTTGG-TAGAGCAGTTGACTTTTAATCAATTGGTCACA...,TTAGCTCAGTTGGATAGAGCAACGGCCTTCTAAGCCGTAGATCACA...
655,G00009306,G90004803,79.365,63,12,1,66807,66868,180899,180961,3.414670,37,CTTAGCTCAGAAGG-TAGAGCAACTGACTTGTAATCAGTAGGTCAC...,CTTAGCTCAGTTGGATAGAGCAACGGCCTTCTAAGCCGTAGATCAC...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
45,G00009306,G90004803,96.25,80,3,0,237422,237501,367908,367987,2.731730e-30,137,GTGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATT...,GTGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATT...
293,G00009306,G90004803,80.00,60,12,0,66808,66867,367916,367975,4.359280e-03,46,TTAGCTCAGAAGGTAGAGCAACTGACTTGTAATCAGTAGGTCACCA...,TTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTGGTCGCAG...
502,G00009306,G90004803,100.00,20,0,0,470119,470138,367916,367935,9.006620e-01,39,TTAGCTCAGTTGGTAGAGCA,TTAGCTCAGTTGGTAGAGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
507,G00009306,G90004803,100.0,20,0,0,2012,2031,410091,410110,0.900662,39,TTTTTTTTAAATTAATTATA,TTTTTTTTAAATTAATTATA
508,G00009306,G90004803,100.0,20,0,0,15612,15631,410110,410091,0.900662,39,TATAATTAATTTAAAAAAAA,TATAATTAATTTAAAAAAAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
8,G00009306,G90004803,72.621,1366,374,0,273681,275046,453270,454635,2.024550e-130,469,TAATTACGATCAATAATTTCTTTTACTTCCTTATCTACAGATCTAG...,TAATTACGTTCAATAAGAACTTTTACCTCTTGATCAATAATTCGCG...
515,G00009306,G90004803,100.000,20,0,0,380366,380385,454178,454197,9.006620e-01,39,ATCAATTTCATCGATAAAAA,ATCAATTTCATCGATAAAAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
531,G00009306,G90004803,100.0,20,0,0,4128,4147,537905,537924,0.900662,39,ATTAATAAAAATTGAATTAT,ATTAATAAAAATTGAATTAT
532,G00009306,G90004803,100.0,20,0,0,13495,13514,537924,537905,0.900662,39,ATAATTCAATTTTTATTAAT,ATAATTCAATTTTTATTAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
62,G00009306,G90004803,76.279,215,51,0,7300,7514,555619,555833,4.420980e-25,119,AGATTGAAGAAAAGTTTTCTTTGTGCTTTTGTTGTTGCAACTTTCA...,AGATTAAAGAATAGCTTACGTTGTGCTTTTGTAGTCGCCACTTTTA...
534,G00009306,G90004803,87.500,32,4,0,573828,573859,555800,555769,9.006620e-01,39,ATTCAAGAAGGAAACATAGGATTAATGAAAGC,ATTCAAGAAGGAAACATCGGCATGATGAAAGC
535,G00009306,G90004803,87.500,32,4,0,555840,555871,555769,555800,9.006620e-01,39,GCTTTCATTAATCCTATGTTTCCTTCTTGAAT,GCTTTCATCATGCCGATGTTTCCTTCTTGAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
62,G00009306,G90004803,76.279,215,51,0,7300,7514,555619,555833,4.420980e-25,119,AGATTGAAGAAAAGTTTTCTTTGTGCTTTTGTTGTTGCAACTTTCA...,AGATTAAAGAATAGCTTACGTTGTGCTTTTGTAGTCGCCACTTTTA...
535,G00009306,G90004803,87.500,32,4,0,555840,555871,555769,555800,9.006620e-01,39,GCTTTCATTAATCCTATGTTTCCTTCTTGAAT,GCTTTCATCATGCCGATGTTTCCTTCTTGAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
180,G00009306,G90004803,89.583,48,5,0,66802,66849,587023,587070,2.693610e-08,64,GCCGGCTTAGCTCAGAAGGTAGAGCAACTGACTTGTAATCAGTAGGTC,GCCGGCATAGCTCAGTTGGTAGAGCAATTGATTTGTAATCAGTAGGTC
214,G00009306,G90004803,83.929,56,9,0,237431,237486,587030,587085,5.565200e-06,56,TAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTGGTCACAGG...,TAGCTCAGTTGGTAGAGCAATTGATTTGTAATCAGTAGGTCGAGGG...
540,G00009306,G90004803,87.500,32,4,0,437090,437121,587048,587017,9.006620e-01,39,TGCTCTACCTACTGAGCTATTCGGGCAACAAA,TGCTCTACCAACTGAGCTATGCCGGCATCAAA
761,G00009306,G90004803,100.000,19,0,0,242069,242087,587029,587047,3.414670e+00,37,ATAGCTCAGTTGGTAGAGC,ATAGCTCAGTTGGTAGAGC
762,G00009306,G90004803,100.000,19,0,0,470120,470138,587030,587048,3.414670e+00,37,TAGCTCAGTTGGTAGAGCA,TAGCTCAGTTGGTAGAGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
546,G00009306,G90004803,100.0,20,0,0,473493,473512,602292,602311,0.900662,39,TATCTTCAGAAATTAATGAA,TATCTTCAGAAATTAATGAA
547,G00009306,G90004803,87.5,32,4,0,421067,421098,602334,602303,0.900662,39,GAGTACAGTTCAACAATTAAATGTTCATTAAT,GAGTAAAGTTCGACAATCAGATGTTCATTAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
38,G00009306,G90004803,100.0,78,0,0,242152,242229,28582,28659,2.426220e-34,150,TTCGGCGAGTGGCGCAGCTTGGTAGCGCAACTGGTTTGGGACCAGT...,TTCGGCGAGTGGCGCAGCTTGGTAGCGCAACTGGTTTGGGACCAGT...
601,G00009306,G90004803,100.0,19,0,0,46803,46821,28647,28629,3.414670e+00,37,AGGATTTGAACCTCCGACC,AGGATTTGAACCTCCGACC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
611,G00009306,G90004803,95.455,22,1,0,7742,7763,51190,51211,3.41467,37,AGATTAAATAATATTCAAAAAT,AGATTAAATAATATCCAAAAAT
612,G00009306,G90004803,95.455,22,1,0,9879,9900,51211,51190,3.41467,37,ATTTTTGAATATTATTTAATCT,ATTTTTGGATATTATTTAATCT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
664,G00009306,G90004803,92.0,25,2,0,552532,552556,214127,214151,3.41467,37,CAAGAAAACTTTATTAATTGAAATA,CAAGAAAATTTTAATAATTGAAATA
665,G00009306,G90004803,100.0,19,0,0,470621,470639,214130,214148,3.41467,37,GAAAATTTTAATAATTGAA,GAAAATTTTAATAATTGAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
680,G00009306,G90004803,83.784,37,6,0,518406,518442,291367,291403,3.41467,37,AATTTTTTTGTTGTTAATGAGTTAATTTGACTTATAA,AATTTTTATGCTTTTAATAAATTAATTTGACCTATAA
681,G00009306,G90004803,92.000,25,2,0,473668,473692,291369,291393,3.41467,37,TTTTTATGTTTTTAATAAATCAATT,TTTTTATGCTTTTAATAAATTAATT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
497,G00009306,G90004803,92.308,26,2,0,176025,176050,351146,351171,0.900662,39,AAAAATTTTTTTAAAATATTCAATAT,AAAAATTTTTTAAAAATATTGAATAT
693,G00009306,G90004803,89.286,28,3,0,375893,375920,351165,351138,3.414670,37,AATATTTTTAGATATTTTTTTAAAGAAT,AATATTTTTAAAAAATTTTTTAAAGAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
45,G00009306,G90004803,96.250,80,3,0,237422,237501,367908,367987,2.731730e-30,137,GTGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATT...,GTGGGTCGTTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATT...
293,G00009306,G90004803,80.000,60,12,0,66808,66867,367916,367975,4.359280e-03,46,TTAGCTCAGAAGGTAGAGCAACTGACTTGTAATCAGTAGGTCACCA...,TTAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTGGTCGCAG...
502,G00009306,G90004803,100.000,20,0,0,470119,470138,367916,367935,9.006620e-01,39,TTAGCTCAGTTGGTAGAGCA,TTAGCTCAGTTGGTAGAGCA
702,G00009306,G90004803,81.395,43,8,0,555171,555213,367971,367929,3.414670e+00,37,GGATTCGAACCAGCGACCAAACGATTATGAGTCGTCTGCTCTA,GGACTCGAACCTGCGACCAATTGATTAAAAGTCAACTGCTCTA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
703,G00009306,G90004803,87.097,31,4,0,562284,562314,368216,368186,3.41467,37,AAATAGATATTTAATTTCTTAGTTTTTTTAT,AAATAGATTTTTTATCTATTAGTTTTTTTAT
704,G00009306,G90004803,87.097,31,4,0,567385,567415,368186,368216,3.41467,37,ATAAAAAAACTAAGAAATTAAATATCTATTT,ATAAAAAAACTAATAGATAAAAAATCTATTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
61,G00009306,G90004803,79.781,183,30,7,46792,46970,381228,381407,4.420980e-25,119,ACGCATCCAGAAGGATTTGAACCTCCGACCTCTCGGTTCGTAGCCG...,ACGCATCCGAGAGGATTCGAACCTCCGACCGCTCGGTTCGTAGCCG...
706,G00009306,G90004803,95.455,22,1,0,242199,242220,381257,381236,3.414670e+00,37,GGTCGGAGGTTCAAATCCTCTC,GGTCGGAGGTTCGAATCCTCTC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
89,G00009306,G90004803,90.667,75,6,1,564831,564904,408805,408879,1.478240e-17,94,AATCCTCCATAGTTCAGATGGTAGAACGGCGGACTGTTAATCCGTA...,AATCCTCTGTAGTTCAGTTGGTAGAACGGCGGACTGTTAATCCGTA...
711,G00009306,G90004803,78.182,55,12,0,237431,237485,408814,408868,3.414670e+00,37,TAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTGGTCACAGG...,TAGTTCAGTTGGTAGAACGGCGGACTGTTAATCCGTATGTCACTGG...

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
118,G00009306,G90004803,71.91,267,75,0,264124,264390,441930,442196,1.664380e-13,81,AATTTTGAGATCCATTTGTAAAGCACTGATTCCTTCTTCATTTCCC...,AATTTTGATATCCATTTGAAATGCAGTTATACCTTCACGACTACCA...
719,G00009306,G90004803,92.00,25,2,0,281877,281901,442028,442052,3.414670e+00,37,ATAAAATAATAAATTTGTAACCTTT,ATAATATAATAAATTTGTCACCTTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
119,G00009306,G90004803,86.364,88,8,4,270687,270773,450357,450441,1.664380e-13,81,ATACCGAGGACGGGAATTGAACCCGTATGCCAAACTAAGAGGCACT...,ATACCGAGGACGGGACTTGAACCCGTAAGCCCAACTG---GGCACT...
721,G00009306,G90004803,100.000,19,0,0,219457,219475,450382,450364,3.414670e+00,37,ACGGGTTCAAGTCCCGTCC,ACGGGTTCAAGTCCCGTCC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
748,G00009306,G90004803,92.000,25,2,0,347795,347819,531909,531933,3.41467,37,TTTAATCAAAAATGAATAATTTTTT,TTTAATAAAAAATAAATAATTTTTT
749,G00009306,G90004803,89.286,28,3,0,282934,282961,531944,531917,3.41467,37,TAATATTTTCGAAAAAATTATTTTTTTT,TAATATTTTAAAAAAAATTATTTATTTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
750,G00009306,G90004803,89.286,28,3,0,17417,17444,534504,534531,3.41467,37,ATTATAAAATTGAAACTCGATTTATATT,ATTATAAATTTGAAACTAGATTTTTATT
751,G00009306,G90004803,89.286,28,3,0,202,229,534531,534504,3.41467,37,AATATAAATCGAGTTTCAATTTTATAAT,AATAAAAATCTAGTTTCAAATTTATAAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
180,G00009306,G90004803,89.583,48,5,0,66802,66849,587023,587070,2.693610e-08,64,GCCGGCTTAGCTCAGAAGGTAGAGCAACTGACTTGTAATCAGTAGGTC,GCCGGCATAGCTCAGTTGGTAGAGCAATTGATTTGTAATCAGTAGGTC
761,G00009306,G90004803,100.000,19,0,0,242069,242087,587029,587047,3.414670e+00,37,ATAGCTCAGTTGGTAGAGC,ATAGCTCAGTTGGTAGAGC

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
180,G00009306,G90004803,89.583,48,5,0,66802,66849,587023,587070,2.693610e-08,64,GCCGGCTTAGCTCAGAAGGTAGAGCAACTGACTTGTAATCAGTAGGTC,GCCGGCATAGCTCAGTTGGTAGAGCAATTGATTTGTAATCAGTAGGTC
214,G00009306,G90004803,83.929,56,9,0,237431,237486,587030,587085,5.565200e-06,56,TAGCTCAGTTGGTAGAGCAGTTGACTTTTAATCAATTGGTCACAGG...,TAGCTCAGTTGGTAGAGCAATTGATTTGTAATCAGTAGGTCGAGGG...
762,G00009306,G90004803,100.000,19,0,0,470120,470138,587030,587048,3.414670e+00,37,TAGCTCAGTTGGTAGAGCA,TAGCTCAGTTGGTAGAGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
542,G00009306,G90004803,100.0,20,0,0,470120,470139,587494,587513,0.900662,39,TAGCTCAGTTGGTAGAGCAC,TAGCTCAGTTGGTAGAGCAC
763,G00009306,G90004803,100.0,19,0,0,237431,237449,587494,587512,3.414670,37,TAGCTCAGTTGGTAGAGCA,TAGCTCAGTTGGTAGAGCA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
765,G00009306,G90004803,82.5,40,7,0,547402,547441,617709,617748,3.41467,37,ATTTTATTAATTAATTCTTTGTTAATTTTATTTGAAAAAT,ATTTTATTAATTAAATCTATTAAAATTTTATATTAAAAAT
766,G00009306,G90004803,92.0,25,2,0,305204,305228,617761,617737,3.41467,37,ATTTTTGATATCTATTTTTAAGATA,ATTTTTGAAATCTATTTTTAATATA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
797,G00009306,G90004803,95.455,22,1,0,114759,114780,723769,723790,3.41467,37,ATTATTTATAAATCAATAAAAA,ATTATTTAGAAATCAATAAAAA
798,G00009306,G90004803,85.294,34,5,0,537944,537977,723821,723788,3.41467,37,TCTAAAAAAATTTTAGAATATTATAAAAATATTT,TCTAATCAAATATTAGAATTTTGTAAAAATATTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
799,G00009306,G90004803,92.0,25,2,0,557548,557572,728111,728087,3.41467,37,TTCATATTTAGAAATATTAAAATTT,TTCATTTTTAGAAATATTAATATTT
800,G00009306,G90004803,92.0,25,2,0,572127,572151,728087,728111,3.41467,37,AAATTTTAATATTTCTAAATATGAA,AAATATTAATATTTCTAAAAATGAA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
803,G00009306,G90004803,95.455,22,1,0,76428,76449,737121,737142,3.41467,37,TTTATACTGGAAAAATTATTAT,TTTATACTGAAAAAATTATTAT
804,G00009306,G90004803,100.000,19,0,0,333040,333058,737145,737127,3.41467,37,AAAATAATAATTTTTTCAG,AAAATAATAATTTTTTCAG

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
809,G00009306,G90004803,89.286,28,3,0,139141,139168,775514,775541,3.41467,37,TTTTTTAAAATTTATTTTTAATAAATAG,TTTTATAAAATATATTTTTGATAAATAG
810,G00009306,G90004803,92.000,25,2,0,477556,477580,775544,775520,3.41467,37,AAACTATTTTTCAAAGATATATTTT,AAACTATTTATCAAAAATATATTTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
570,G00009306,G90004803,100.000,20,0,0,496778,496797,779910,779891,0.900662,39,ATATTTCATTTTTTTTAAAA,ATATTTCATTTTTTTTAAAA
811,G00009306,G90004803,89.286,28,3,0,326789,326816,779915,779888,3.414670,37,ATTTGATATTTCATTTTAAATAAAAATA,ATTTGATATTTCATTTTTTTTAAAAATA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
438,G00009306,G90004803,92.593,27,2,0,240349,240375,796074,796100,0.237561,41,CTAAGTCATTATTTTTTTTGAAAAATT,CTAAGTAATTATTTTTTTGGAAAAATT
820,G00009306,G90004803,92.000,25,2,0,352711,352735,796099,796075,3.414670,37,ATTTTTCCAAAAAAATAAGAACTTA,ATTTTTCCAAAAAAATAATTACTTA

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
834,G00009306,G90004803,100.0,19,0,0,12822,12840,832422,832440,3.41467,37,ATGTTCGTAATGTGAATTT,ATGTTCGTAATGTGAATTT
835,G00009306,G90004803,100.0,19,0,0,4802,4820,832440,832422,3.41467,37,AAATTCACATTACGAACAT,AAATTCACATTACGAACAT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
857,G00009306,G90004803,87.097,31,4,0,572127,572157,903984,903954,3.41467,37,AAATTTTAATATTTCTAAATATGAAAATATA,AAATTTTAAAATATCTATATATGCAAATATA
858,G00009306,G90004803,87.097,31,4,0,557542,557572,903954,903984,3.41467,37,TATATTTTCATATTTAGAAATATTAAAATTT,TATATTTGCATATATAGATATTTTAAAATTT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
221,G00009306,G90004803,80.488,82,13,3,224305,224386,908224,908302,0.000006,56,CGGGAAGCGAGACTTGAACTCGCAAAACCATTTTTGGTGCTAGATC...,CGGGAGGCGAGACTTGAACTCGCAAACC---TTACGGCGCCAGAAC...
859,G00009306,G90004803,95.455,22,1,0,503346,503367,908277,908298,3.414670,37,TGCGTTTACCAATTTCGCCACT,TGCGTCTACCAATTTCGCCACT

,queryAccVer,subjectAccVer,identity,alignmentLength,mismatches,gaps,qStart,qEnd,sStart,sEnd,evalue,bitScore,qSeq,sSeq
860,G00009306,G90004803,89.286,28,3,0,5446,5473,909407,909434,3.41467,37,AAAATTAGATATAGAGAATGTTTAAAAA,AAACTTAGATATAGAAAATTTTTAAAAA
861,G00009306,G90004803,89.286,28,3,0,12169,12196,909434,909407,3.41467,37,TTTTTAAACATTCTCTATATCTAATTTT,TTTTTAAAAATTTTCTATATCTAAGTTT

看一眼 blastn有没有overlapping region in seq A mapped to two subseqs in seq B